### ISSUE TITLE
Design of graph

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#10]
https://www.dropbox.com/s/dnq493th4twt5hu/Screenshot%202019-08-17%2009.00.39.jpg?dl=0

100% should have the same left padding as each 0%

**Comment by iambateman** [comment]
This is purposeful. The graph looks best when all the percentage signs line up, like this:
https://www.dropbox.com/s/rvzkj0ndzolr8y9/Screenshot%202019-08-17%2009.02.08.jpg?dl=0 

The % is right aligned, and the label is left aligned to keep consistency.

**Comment by oburbank** [comment]
that makes sense to me
