### ISSUE TITLE
Embed results-only after poll is closed

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#104]
Currently the embed works for voting, but VCMA requests being able to embed results without the ability to vote. Is this already "built in" more or less when voting is closed on a poll? I think the logic is fairly straightforward: when the poll is closed, the embed goes straight to results.

**Comment by iambateman** [comment]
The challenge here is that the embed is just a small version of the vote page, so how it works on the app is how it needs to work on the embed.

**Comment by iambateman** [comment]
But we can probably figure out a way to do this.

**Comment by iambateman** [comment]
not probably. can.

**Comment by proggeramlug** [comment]
this can now be tested, I'll provide a dev-URL shortly

**Comment by ggordn3r** [comment]
I embedded this on a hidden page on Koios to test out. See https://www.koios.co/settings

I am using this poll: https://rankit.skelpo.com/polls/h2rjTQZMM4PYtsDAbQZv

I saw a "voting has concluded" message for a split-second, but as soon as I clicked "View Results", I always see this on reload:
![Screenshot (253)](https://user-images.githubusercontent.com/10144772/80258844-356d0980-8652-11ea-96c3-689fb779d5ab.png)

That is a problem because the person viewing didn't actually vote. Insted, the results-only embed should start on the "Final Results" screen:

![Screenshot (254)](https://user-images.githubusercontent.com/10144772/80258923-66e5d500-8652-11ea-999b-e04984410bac.png)

**Comment by proggeramlug** [comment]
Replace "https://rankit.vote/" with "https://rankit.skelpo.com/" and it _should_work ;) You embedded the live version, which doesn't have this update (yet).
