### ISSUE TITLE
As a super user, I can embed custom HTML as my call-to-action

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#105]
VCMA is asking for API integration with EveryAction (their mailing list system) on the call-to-action page. Instead, what do you think about allowing super users to embed custom HTML? That way they could embed their existing EveryAction signup page instead of relying on a questionable API setup.

**Comment by iambateman** [comment]
yes. that makes a lot of sense.

**Comment by proggeramlug** [comment]
@ggordn3r would this be added to the current CTA or would that be a replacement?

**Comment by ggordn3r** [comment]
Ideally, while creating a poll you could choose between two options:

Current option: button/link
New option: Use custom HTML

*Trey Gordner*
Founder, Koios
(803) 570-2144
Website <https://www.koios.co> | Twitter <https://twitter.com/koioslib> | Join
our Newsletter <https://www.koios.co/join-koios-newsletter/>
*Helping libraries show up online*

**Comment by proggeramlug** [comment]
this can now be tested, I'll provide a dev-URL shortly

**Comment by ggordn3r** [comment]
The UX for this looks good in the create poll section, but because I can't vote in the poll, I can't test fully. See #109 for details.

**Comment by ggordn3r** [comment]
I tested this with a Youtube video, but am still having trouble voting on newly created polls, so I couldn't finish testing it with a Mailchimp form. Seems to work ok so far, but can the block be centered on the page? It irks me a little that this video is left justified :D

![Screenshot (258)](https://user-images.githubusercontent.com/10144772/80323175-d3e69f80-87f7-11ea-92c8-e2d06058d70e.png)

**Comment by ggordn3r** [comment]
I was able to test this and it works well. I am concerned, though, that it could result in a new request for a "preview mode" of the custom HTML.

If that does happen, the best way to handle it is: add a "Preview" option to the page where the "Publish" option resides while the poll is in Draft.
