### ISSUE TITLE
As a poll creator, I can "hold results" until the poll is closed

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#106]
Poll creators want the ability to "hold results"--I'm thinking this is just another state like "there aren't enough votes yet to show results", but instead it says "results are being held until polls close. In the meantime..." or "results will be revealed at [TIME]"

Option A: this could be linked to the existing time limit setting when creating a poll (e.g. "keep open for 7 days"). I'm wondering if we should rework that to say "Keep poll open until" and use a date/time picker instead. It seems like users want that kind of precision, especially for live events. If we do that, then perhaps there could simply be a "hold results until polls close" checkbox underneath that field. 

Option B: Alternatively, "hold/show results" could just be a toggle in the poll management page (Probably with an "are you sure?" validation). However, keep in mind that a poll creator may already be in presentation mode (#91), so if we use a toggle it may need to appear there as well.

**Comment by iambateman** [comment]
If we do Option B, it's simple. Can we do that?

**Comment by proggeramlug** [comment]
Option B is implemented and can be tested!

**Comment by ggordn3r** [comment]
Functionally, this works great. We just need slight changes to the language:

1) If the toggle is set to "Do not show results", the "View Results" button should be disabled in the poll creator view.

2) If the poll is set to "Do not show results", the message on [Results Summary](https://rankit.skelpo.com/results/h2rjTQZMM4PYtsDAbQZv/summary) should read:
_The creator of this poll is currently holding the results. Please check back later._
(This message is the same whether the poll is set to "Open" or "Closed"--currently it varies)

**Comment by proggeramlug** [comment]
1. done.
2. done
3. done

:)

**Comment by ggordn3r** [comment]
Tested all 3--1 and 3 are good to go, but I still see the previous text when the poll is closed and "Do not show results" is selected:

![image](https://user-images.githubusercontent.com/10144772/80823883-6649c300-8bab-11ea-917f-7dda3924e395.png)

**Comment by proggeramlug** [comment]
This is implemented now and can be tested. (the Alternative solution)

**Comment by ggordn3r** [comment]
Can't test due to #120

**Comment by ggordn3r** [comment]
Tested this, but am still seeing screenshot below as poll creator. Only those who are not the poll creator should see this message--the poll creator should see the actual results in both cases as described in my the comment above.

![creator cannot see results](https://user-images.githubusercontent.com/10144772/81020883-da989680-8e37-11ea-9a36-84426419e188.jpg)

**Comment by proggeramlug** [comment]
I can't reproduce this issue, can you test again? If it still happens try on the computer, It has to work :D 

I reworded the button, making it two lines looked worse ;)

**Comment by ggordn3r** [comment]
I think I may know the issue. Each of the polls I tested had votes before they were published. (I had created them on rankit.vote before we created the staging domain). See, for example this one:
https://rankit.skelpo.com/results/ypZy2L5IZuulZi6Zfzu3/summary

By contrast, I created this one on rankit.skelpo.com and it behaves as expected:
https://rankit.skelpo.com/results/rDZnWYOUBh5BbaSUvF1b/summary

Can you confirm that is the likely cause?

Also, I appreciate the reword but I'm seeing "only for to you" which is not grammatical. Did you try "only you can view"? I think that will fit on my screen.

**Comment by proggeramlug** [comment]
Yes, that makes sense actually. Because we don't have our flag "results_public" set yet (it does not exist on that poll)

I'll add that to all existing polls together with the draft/published flag.

I must have been tired, I picked your wording - check it out. I meant to say "only for you" FWIW ;)

**Comment by ggordn3r** [comment]
I saw you add that to the other issue. Sounds good.

Unfortunately, that _still_ doesn't fit on my phone. Ugh. What if the fa-signal icon disappears when the poll is set to "Do not show results"? That would give us a lot of room.

**Comment by proggeramlug** [comment]
done, check it now!

**Comment by ggordn3r** [comment]
FINALLY! :D
