### ISSUE TITLE
Log events in Firebase Analytics for significant events

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#108]
As an admin, I want to count significant events so I can track how the site is used over time.

Firebase has a built-in analytics library and we've already set it up. Now we just need to log a few events to it.

How to log events in Firebase:
https://firebase.google.com/docs/analytics/events

We want events for:
- "new_account" when someone creates an account
- "published_poll" when someone publishes a poll
- "new_vote" when someone votes in a poll

Ideally, published_poll would include these custom parameters: user_id, poll_id, # of winners, # of choices
Ideally, new_vote would include these custom parameters: poll_id, # of choices, # of choices ranked

**Comment by ggordn3r** [comment]
**For Trey's reference -- ignore**

Super User Dashboard for states allies - shows their polls not all polls (admin dashboard would show all polls) Exporting emails of those who have logged in. 
Ideas:
# of votes, # of voters, # of polls, # of new accounts
Device breakdown: mobile vs. tablet vs. desktop
Acquisition: where are people coming from?
Average votes/poll
Geographic report: where are Rankit.Vote visitors coming from?
Cohort analysis: do people return to vote on more than one poll? Create more than one poll?
Conversion tracking: how many people vote vs. bounce?
How many choices do people rank on average? Compare to total # of choices.
How often do people click on the Call-To-Action at the end?
How often do people share polls? Embed?

**Comment by proggeramlug** [comment]
Do I need to do something here?

**Comment by ggordn3r** [comment]
Yes, add a `logEvent()` method to the relevant spots in the code (see linked documentation).

**Comment by proggeramlug** [comment]
This should be done now, it may take a little before the events show though.

**Comment by ggordn3r** [comment]
Ok, I'll wait and check on this tomorrow.

**Comment by ggordn3r** [comment]
No sign of the new events in Firebase. Is that because we're only logging traffic on prod?

![Screenshot (146)](https://user-images.githubusercontent.com/10144772/90413077-fbe66100-e07b-11ea-8e3a-1634230d3e00.png)

**Comment by proggeramlug** [comment]
MIght be, it would be worth testing that first before trying to find a needle in a haystack.

**Comment by ggordn3r** [comment]
Metrics are suspiciously low--is it possible that the tracking code was deleted when we migrated from staging? It should be on every page. See Firebase Console --> Analytics over the past 6 months.

Also, we're missing one of the requested metrics: new_account.

**Comment by ggordn3r** [comment]
I just checked and I don't see the Firebase SDK code snippet in the page source for /home anymore:
https://firebase.google.com/docs/analytics/get-started
view-source:https://rankit.vote/home
It should be on all pages. 

Also see my last comment about missing one of the requested metrics. That should be an "event" triggered by creating a new account.

**Comment by proggeramlug** [comment]
Hmm, I updated to the latest dependency and redeployed. We need to see, the events are a little delayed but we did not change the config.

Also, the JS for analytics would be hidden in our other files, I don't think you would see it in the HTML.

**Comment by ggordn3r** [comment]
Ok, but something happened on or around Sept 1 that seems to have broken our measurement. We were seeing 100-400 users a day before that and afterwards it reported 0-1. I know that's wrong because of all the bug reports we've been getting.

I'm seeing a lot of "realtime" users right now, so I'll leave this open and check again next week to see if updating the dependencies fixed the issue.

![image](https://user-images.githubusercontent.com/10144772/96299802-99013f80-0fc2-11eb-93ad-3a4d185bf61c.png)
