### ISSUE TITLE
Unable to log in via Facebook (secure connection?)

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#110]
See screenshot for error one user received when trying to log in via Facebook:

![Facebook login screenshot Chrome](https://user-images.githubusercontent.com/10144772/77800885-22b0e600-704e-11ea-9021-5a23a3b46cd1.png)

**Comment by ggordn3r** [comment]
I have tried to reproduce this since but am unable. Facebook login works fine for me. @proggeramlug, any ideas?

**Comment by proggeramlug** [comment]
@ggordn3r probably related to #93 which we will take care of once we deploy to the live system

**Comment by ggordn3r** [comment]
Ok, I will close this on that assumption.
