### ISSUE TITLE
Refresh on rankit.skelpo.com causes 404 on all pages

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#112]
Not sure what to make of this one. If I refresh the page while voting, I get this message:
"Not Found
The requested URL /vote/zDvGganVwjdYGafT2mLh was not found on this server."

This also happens when I refresh on /home and persists if I click back/forward, but if I reenter rankit.skelpo.com/ it seems to reset the issue.

![Screenshot (246)](https://user-images.githubusercontent.com/10144772/79912062-6dc0dd80-83ef-11ea-9b3b-8011e35ac6ee.png)

**Comment by proggeramlug** [comment]
This has been fixed.
