### ISSUE TITLE
Cannot login with OAuth on rankit.skelpo.com

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#113]
Looks like just an easy configuration update--Firebase doesn't know that this is the staging environment. Here's the error I get on attempting login via Facebook:

Error: This domain (rankit.skelpo.com) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

![Screenshot (247)](https://user-images.githubusercontent.com/10144772/79912257-bd9fa480-83ef-11ea-8c19-f7aa72927609.png)

**Comment by proggeramlug** [comment]
Fixed
