### ISSUE TITLE
Add "My recent polls" to home page

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#114]
The home page adds ‘my recent polls’ which is just the three newest polls from a user. For desktop and mobile. 

![Desktop – home](https://user-images.githubusercontent.com/10144772/80378028-0f21b680-886a-11ea-9b88-e063739022f5.png)
See screenshot.

**Comment by ggordn3r** [comment]
Well, I was planning on saving this for later, but because you did it already, I might as well pull it into the Priority project 😃 

I noticed a bug--"My Recent Polls" still tries to fetch polls even when a user is not logged in:
![Screenshot (276)](https://user-images.githubusercontent.com/10144772/80768172-a6f7fc80-8b17-11ea-9234-99e052852b93.png)

**Comment by proggeramlug** [comment]
All fixed, live, and ready for you to test.

**Comment by ggordn3r** [comment]
Confirmed!
