### ISSUE TITLE
All issues marked 'draft'

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#115]
Copying Trey first to make sure this isn't known already.

When I logged in, it showed all my current polls as 'draft', when they were published. Existing polls should default to 'published'

**Comment by proggeramlug** [comment]
@ggordn3r we need to do this before we go live .. :)

**Comment by ggordn3r** [comment]
Will we need to do it twice, once for the staging environment and once for the live one?

Either way, agreed. All yours!

**Comment by proggeramlug** [comment]
No, we use the same database, so only once.

**Comment by proggeramlug** [comment]
also "results_public" needs to be set to true

**Comment by proggeramlug** [comment]
This is done now
