### ISSUE TITLE
Make multi-winner polls more obvious

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#117]
Multi-winner polls are not as intuitive as single-winner, so we need to constantly remind the user that they're looking at one. I propose 2 slight improvements:

1) In a new line under the Poll Title, include "(N winners)" in the same style as the body text.
**Update 7/27/20:** Make this "(N winners, T% to win)", where N is the # of winners and T is the threshold value.

2) At the end of the "We have a winner!" paragraph in multi-winner polls, append the number of winners left like this:

_We have a winner! Sen. Elizabeth Warren of Massachusetts wins with 40% of the vote. Two more winners will be chosen._

**Comment by proggeramlug** [comment]
Okay, the first part I've implemented.

The second part, do you have an example poll where this could be tested well? I struggle to find/create one.

**Comment by ggordn3r** [comment]
Hmm... this could be an issue with the threshold for the "Heads Up" message. I've voted 10 times in this multi-winner poll (https://rankit.skelpo.com/results/rDZnWYOUBh5BbaSUvF1b/summary). I thought the threshold was 7.

**Comment by ggordn3r** [comment]
Also, see the update in the description as of 7/27--slight wording addition request from the client.

**Comment by proggeramlug** [comment]
The threshold is not 7, the threshold is `poll.choices.length * 2 + 1` so in this case 15*2+1 = 31.

Is that by design or should we change it to 7?

**Comment by ggordn3r** [comment]
Is `poll.winners.length*2 + 1` an option? That would be ideal.

**Comment by proggeramlug** [comment]
Okay, changed it to the winner-length and implemented the second part - take a look!

**Comment by ggordn3r** [comment]
A couple of tweaks:
1) I don't see the message specified in part 1 above. I mocked it up exactly as it should look in the screenshot below.
2) Part 2 number is wrong in the poll I tested, see screenshot for details:
https://rankit.skelpo.com/results/ZehVDnsKBEWWvRnIbH8a/1

![Screenshot (26)](https://user-images.githubusercontent.com/10144772/90025670-623a4080-dc84-11ea-82af-e268c75e4b85.png)

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
Found a quirky issue--"winners left" miscounts when there's a tie for 2 winners in the first round:
https://rankit.skelpo.com/results/I4cnPOhEjpqc0mnmo0Pp/1

Notice that it says "2 more winners" but there are 3 total winners and 2 were elected in this round, so it should say "1 more winner"

**Comment by proggeramlug** [comment]
Found the problem and fixed it!
