### ISSUE TITLE
Hitting "Enter" while adding choices during poll creation deletes the first choice

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#118]
It used to be that when I hit "Enter" while typing poll choices, it would automatically create a new choice and place the cursor there. Now nothing happens if there are less than 2 choices, and the first choices is deleted if there are 3 or more.

Before I hit "Enter":
![image](https://user-images.githubusercontent.com/10144772/80750755-a864fd00-8af6-11ea-89ed-54e2bca95d64.png)

After I hit "Enter":
![image](https://user-images.githubusercontent.com/10144772/80750796-b87cdc80-8af6-11ea-91fd-74087db673f8.png)

**Comment by proggeramlug** [comment]
@ggordn3r I'm only seeing this behavior (of adding choices) when hitten "tab", not "enter". Are you sure this was enter at any point?

I've seen the delete happen too, I can see to prevent that, but confirm that we want "enter" to be the one to create new choices.

**Comment by ggordn3r** [comment]
@proggeramlug You're right, I definitely used "Tab" in the past. Let's stick with that and just make enter _not_ delete choices for now.

**Comment by proggeramlug** [comment]
Done
