### ISSUE TITLE
Registering a new user triggers an error

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#121]
**Update:** Confirmed on rankit.skelpo.com as well

Andrea registered as a new user last night and I registered one this morning. Both times we encountered an insufficient permissions error. (Note: unlike Andrea last night, I was able to create a poll after seeing this message)

![Screenshot (288)](https://user-images.githubusercontent.com/10144772/81480127-90c3fd80-91f5-11ea-84a8-eafad8b7d923.png)

**Comment by proggeramlug** [comment]
I'll gladly fix this issue, but we apparently had it before: https://20200212t121732-dot-rankit-vote.uc.r.appspot.com 

:) Just FYI...

**Comment by proggeramlug** [comment]
Should be fixed!
