### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#122]
Andrea and I have both seen a 502 bad gateway error on My Polls. I can't seem to reproduce it at will. Not sure if it's related to #121 or #93, or unique.

![Screenshot (290)](https://user-images.githubusercontent.com/10144772/81480201-15af1700-91f6-11ea-8d05-45111611e0b3.png)

**Update:** I think I managed to reproduce this while logged in as curlytrey@gmail.com (super user) by going to https://rankit.vote/polls, closing the tab, opening up a new tab, and going to https://rankit.vote/polls again. After a few tries, when I try to open the page, even with HTTPS, the page won't load even after minutes and I get a "site is not secure" message in Chrome. Eventually, it responds 502.

**Comment by proggeramlug** [comment]
Should be fixed now!

**Comment by ggordn3r** [comment]
Now when I reload https://rankit.vote/polls it now redirects to /home--should simply reload the current page. No 502 error, though!

**Comment by proggeramlug** [comment]
I need to digg a little deeper here, but I'll find it!

**Comment by ggordn3r** [comment]
I figured this one out, although I think #131 is a different issue. This 502 bad gateway occurs when you request something that's not allowed. For example
- Going to https://rankit.vote/polls without being signed in (correct behavior: redirect to https://rankit.vote/auth/login)

- Going to a "success" page like https://rankit.vote/vote/plnVo4bZmaFFx1J0AwUv/success without voting (correct behavior: redirect to the vote page https://rankit.vote/vote/plnVo4bZmaFFx1J0AwUv/)

**Comment by proggeramlug** [comment]
Finally, found it!

**Comment by ggordn3r** [comment]
Tested each of these cases. One passes, one fails:

Going to https://rankit.vote/polls without being signed in (correct behavior: redirect to https://rankit.vote/auth/login)
**Passes, works as expected now**

Going to a "success" page like https://rankit.vote/vote/plnVo4bZmaFFx1J0AwUv/success without voting (correct behavior: redirect to the vote page https://rankit.vote/vote/plnVo4bZmaFFx1J0AwUv/)
**Fails, loads the success page even if a user hasn't voted**

**Comment by proggeramlug** [comment]
Okay, should work as expected now! (rankit.skelpo.com, not live yet)
