### ISSUE TITLE
Log in as admin, all polls load as "My Polls"

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#123]
I logged in as my trey@koios.co (admin) account and saw over 100 polls that I didn't create under "My Polls"--I think it may be loading all of them?

Also, notice in the screenshot that the menu has an error--it's still showing up as if I am not logged in.

![Screenshot (292)](https://user-images.githubusercontent.com/10144772/81480397-8acf1c00-91f7-11ea-831f-5ff74d7f2852.png)

**Comment by ggordn3r** [comment]
Ok, even weirder, if I click "log in" again, it's showing me a profile page I've never seen before. Is this related to the Angular upgrade?

![Screenshot (293)](https://user-images.githubusercontent.com/10144772/81480425-b05c2580-91f7-11ea-9baf-f06db4a7b93f.png)

**Comment by ggordn3r** [comment]
**Update:** tested on rankit.skelpo.com. My Polls and My Account work as expected, but I noticed strange behavior on the admin-only "Manage Polls" page. It loads all polls, then shows just my polls, then shows all polls again in quick succession (about 1 sec each):

Initial load:
![Screenshot (295)](https://user-images.githubusercontent.com/10144772/81480966-efd84100-91fa-11ea-9a0f-9cc39cffd8a4.png)

About 1 second later:
![Screenshot (296)](https://user-images.githubusercontent.com/10144772/81480969-f8307c00-91fa-11ea-99a8-27d3782eb516.png)

About 1 second later:
![Screenshot (297)](https://user-images.githubusercontent.com/10144772/81480980-0b434c00-91fb-11ea-881a-6d4224e18ce5.png)

**Comment by proggeramlug** [comment]
This should be fixed now, had to do with internal caches.
