### ISSUE TITLE
Cannot open polls

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#124]
When I open any of my polls, I see a blank screen now. Tested with 3 accounts, 3 different user levels. No page with /poll will load, neither on existing or new polls . However, /vote and /results seem to be unaffected.

![image](https://user-images.githubusercontent.com/10144772/81490160-a284bf80-924c-11ea-8e54-673bf0a94c33.png)

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
Works for me! However, 2 users also reported being unable to view their own polls. I just tested and am also unable to even load their vote or result pages. Not sure if this is the same issue or not. See quoted messages and polls below:

```
Hey,
So this is a real poll I’m going to send my friends today. I’ll let you know if they have issues. My husband said the poll didn’t load. 
Does it load for you? - https://rankit.vote/vote/nB75QwIMjJGS5uVOXbxZ
```

```
Hi, 
I create a poll today. five people were able to use it, then it didn’t work. When I click on “View Results” I get a page that says “poll not found”. Can you help? Thanks!!

https://rankit.vote/vote/iS9hZ7oevkDTMFbw4xGT
```

**Comment by proggeramlug** [comment]
Works now!
