### ISSUE TITLE
Add link to login page from reset password page

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#125]
I just changed my password for my personal account. Can we have a link that takes the user back to the sign-in page?

![21980](https://user-images.githubusercontent.com/10144772/81592574-2d200880-938c-11ea-98ef-caecebfdc1a8.jpg)

**Comment by proggeramlug** [comment]
This is a little difficult to implement as this page is not supplied by us but by a plugin - how important is it?

**Comment by ggordn3r** [comment]
Not so important that we need custom code in the plugin. I'm marking this as won't fix.
