### ISSUE TITLE
Does login via FB have any configuration options?

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#126]
Question from a user:

_PS- is there a way to connect FB to the app to sign-in. I click on FB but it want me to sign-in to FB. For some websites, you just have to give FB permission and it signs you in. Same with twitter._

In other words, can you have OAuth open in the app on mobile instead of forcing a regular login, as it does now?

**Comment by proggeramlug** [comment]
Unfortunately completely out of our control. The sites/apps where this works are usually system-supported (like FB on iphone). If you have to log into facebook then the browser at least thinks you were logged out - and there is nothing we can do. :)

**Comment by ggordn3r** [comment]
That's what I thought, but just wanted to confirm. Closing.
