### ISSUE TITLE
Poll with votes somehow unpublished

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#127]
Hey, take a look at this screenshot sent in by a user. The poll is somehow not published, but received 5 votes. Now viewers see "poll not found", as expected for an unpublished poll--but publishing should be non-reversible, so how were the first 5 able to vote?

 The URL is https://rankit.vote/polls/iS9hZ7oevkDTMFbw4xGT. 

![PastedGraphic-1](https://user-images.githubusercontent.com/10144772/81737800-adb33780-9466-11ea-8076-937fa66c65cd.png)

I checked the database and, weirdly, there's not even an `is_published` field in the record, which made me think this may be a different issue than #124. 
![image](https://user-images.githubusercontent.com/10144772/81738189-4fd31f80-9467-11ea-90fa-18b553cf382c.png)

**Comment by proggeramlug** [comment]
Okay, this problem has since been resolved. The votes were probably coming in because the system mistakingly assumed that the poll was published (when voting).

Was this the only problem of this kind?

**Comment by ggordn3r** [comment]
I'm not sure how the system could mistakenly assume a poll was published. For users other than the creator, the "poll not found" page should appear if they navigate to the poll's vote page before it is published. In other words, it should be impossible to vote in an unpublished poll. 

Can you confirm that this is what the code is doing now?

**Comment by proggeramlug** [comment]
Confirmed!

**Comment by ggordn3r** [comment]
A related issue appears to have resurfaced with a new user. Here's the poll:
https://rankit.vote/polls/tbAKwFIRmDRbJ4jcFNfp

It shows "poll not found" on live and staging. When I look at the database, I see `is_published: false` as expected, but also `is_open: true`, which is unexpected. How can a poll be open without being published? That combination doesn't work logically with the draft/publish feature as described in #87.

I checked my own polls and all drafts are also closed, so perhaps this user managed to click some combination of buttons that opened the poll without publishing it. We should find this loophole and close it. 

(FYI, I've asked the user to send me a recording of her retracing her steps exactly with a new poll and am waiting to hear back. But there's no guarantee that she does it the same way twice--we should identify the issue ourselves if possible)

**Comment by proggeramlug** [comment]
There might be a logical flaw in the current live system that can create this condition. The fastest way to resolve this is to upload our current changes and see if this is reproducible.

**Comment by ggordn3r** [comment]
I figured out how this is happening. When I created a poll on mobile, I was able to toggle from "closed" to "open" without publishing the poll:
https://rankit.skelpo.com/polls/dUYPTyt5kYNGEEKEuj7Z

You should not be able to switch a poll to "open" without publishing it, and this should be obvious to the user. I see two options:

A) Clicking that toggle before a poll is published should trigger the "Publish" validation, the same as clicking "Publish Poll" at the bottom. Clicking "OK" publishes and opens the poll. Clicking "Cancel" keeps the poll closed and unpublished.

B) Disable the Open/Closed toggle while poll is not published and add a message underneath the toggle in Closed state (identical in style to the one in Open state now): "To open voting, publish the poll first."

**Comment by proggeramlug** [comment]
Implemented A!
