### ISSUE TITLE
Add a technical difficulties banner

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#128]
Add a banner at the top (see, for example, koios.co) alerting people to current technical issues.

Text should start with the [fa-exclamation-triangle](https://fontawesome.com/icons/exclamation-triangle?style=solid) icon, then read:
`Some users are experiencing periodic difficulties voting and viewing results. We apologize for the inconvenience and will be releasing a fix shortly.`

Then, it should have an "X" that users can click to close it.

**Comment by proggeramlug** [comment]
I'm so darn close to fixing this problem (it's such a weird combination of issues) but I have published this already. Hoping to have a fix later today or early tomorrow!
