### ISSUE TITLE
Missing default Call-To-Action

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#129]
In the last release, we had a default call to action if the poll creator didn't select one. It said "Bring RCV to Your Community" and linked to https://www.fairvote.org/get_involved. Was it commented out in the code? It's no longer visible, but the page should still include it if no other CTA is selected.

**Comment by proggeramlug** [comment]
Found the problem and fixed it!

**Comment by ggordn3r** [comment]
Just tested with this URL and I don't see the fix, even after a refresh with cache override:
https://rankit.skelpo.com/vote/o6OhlgVOkaxmcSDy5WB1/success

Screenshot below.

![Screenshot (352)](https://user-images.githubusercontent.com/10144772/86315140-5c6a2d80-bbf7-11ea-9fa7-2d1ff2be2581.png)

**Comment by ggordn3r** [comment]
The URL isn't right. It currently links to https://www.fairvote.org/ but should link to https://www.fairvote.org/get_involved

Otherwise, looks good on staging!

**Comment by proggeramlug** [comment]
That's a caching problem - the URL is saved to the poll. New polls have the correct URL.

**Comment by ggordn3r** [comment]
Hmm... I just created a brand-new poll and it was still the old URL. See https://rankit.skelpo.com/vote/awqmxvFFf5NdWH4Jfzyc

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
Client made one tiny request on this that I didn't think deserved its own issue: The call-to-action button should open in a new tab by default.

**Comment by proggeramlug** [comment]
True ;) Done!
