### ISSUE TITLE
Choosing number of winners

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#13]
https://www.dropbox.com/s/9jvjcgw2o0m3dun/Screenshot%202019-08-17%2009.06.05.jpg?dl=0

I should be able to choose as many winners as I want. I should not be limited to 3.

**Comment by iambateman** [comment]
When I create a poll with 6 choices, I'm able to see a dropdown with up to 6 winners.
https://www.dropbox.com/s/cjq7qlrbu2inkjy/Screenshot%202019-08-17%2009.06.45.jpg?dl=0

Is that different from what you see?

**Comment by oburbank** [comment]
Not a bug, didn't realize this drop down depends on the number of choices populated.
