### ISSUE TITLE
Bad gateway persists with referral links

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#131]
I received a couple of reports of Facebook links not working, which I thought was related to the overall polls not loading issue. But I'm still encountering a problem even after the Firebase fix.

a) If I go to rankit.vote and click on the featured Video conferencing poll, it loads the "Vote success" page without issue. That's correct behavior, I already voted in the poll.

b) However, if I click a link to the "Vote success" page from a link within Gmail, the page waits a long time, then shows a 502 bad gateway error.

Here's the link: https://rankit.vote/vote/O5z48DDWEe50fsiKXIyw/success
EDIT: I'm also seeing the same behavior on this ^^^ link.

I'm asking for more information from the ones who reported the issue on Facebook, but I think it's the same issue.

**Comment by ggordn3r** [comment]
Update: The failure only occurs on polls that are working. A "Poll not found" error returns instantly for unpublished polls:
https://rankit.vote/results/YZY2A4ieBF4Vkkuajxqj/summary
https://rankit.vote/vote/iS9hZ7oevkDTMFbw4xGT

**Comment by ggordn3r** [comment]
Update: This link was reported as not working about 2 weeks ago but is working now. He provided the actual referral link from Facebook, making it easy to follow the steps:

https://www.facebook.com/flx/warn/?u=https%3A%2F%2Frankit.vote%2Fvote%2FDqWjOnmoLrHjJM1yNAkD%3Ffbclid%3DIwAR1LseVF0rZBedIXIOoI7QwGbtzAJo1z-2axnTiviOux7q04Lp5nDeUy7MI&h=AT0tY4cR-cq2acGGwYGQWrR511ew_Ic8AeTOn0MOuNw4kc8hC1i15NAMIWHP4IlUQ2TaUg8Ptp8i9QYTfnQfsABJLEO9HV3TueiBXes7xATwc0Dk98vJW-Xjotm9x5CFjqc&_rdr

**Comment by ggordn3r** [comment]
Tested all links above and they worked as expected, and no new reports of 502's since the fix. Hence, closing.

**Comment by ggordn3r** [comment]
I'm no longer seeing a "bad gateway" error, but this more recent poll shared on Facebook still leads to a "nothing found" page and even shows it in the meta title (see screenshot below).

When I **typed** the URL in the browser, I got a "nothing found" page (I confirmed several times that every digit was correct). However, then I signed in as an admin, went to "manage polls", located the poll by title, clicked through to the /polls page (though I was unable to load it, as mentioned in #136) and switched /polls to /vote in the URL to get to the vote page.

Sure enough, when I did that, the [vote page](https://rankit.vote/vote/2dRIuBr22njWRKVXGp7U) loaded without issue instead of showing "nothing found" like before.

<img width="573" alt="Screen Shot 2020-06-18 at 11 46 15 AM (1)" src="https://user-images.githubusercontent.com/10144772/86318236-655efd00-bbff-11ea-8fd1-5355e5680bd4.png">

**Comment by proggeramlug** [comment]
Can you confirm that this: https://rankit.vote/vote/2dRIuBr22njWRKVXGp7U loads correctly in every browser for you?

**Comment by ggordn3r** [comment]
Loads in Chrome, Edge, Firefox. Unfortunately, I don't have a Mac to test Safari. It seems to consistently appear for a second, then disappear again for 1 second, then load normally.

**Comment by proggeramlug** [comment]
Is that acceptable? It's partially due to the way the site works when loading the page completely new.

Safari on Mac works for me.

**Comment by ggordn3r** [comment]
I just tested all links again. The "blinking" effect still happens from the Facebook and Gmail links, but it's very short in both cases so I'm deeming it acceptable.
