### ISSUE TITLE
CTA button text does not wrap to 2nd line

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#132]
See attached screenshot from a user--when the button text is too long, it exceeds the width of the page.

Expected behavior: text wraps to a second line and button maintains a left and right margin from the edge of the page (try 5px)

![68329](https://user-images.githubusercontent.com/10144772/86287943-2016dd00-bbb7-11ea-9694-7cfbb24004cc.jpg)
lines

**Comment by proggeramlug** [comment]
This has been fixed!

**Comment by ggordn3r** [comment]
Works on mobile, but not on desktop. See this poll as an example:
https://rankit.skelpo.com/vote/hvN6hlmGsMqj3bO2IlP4/success

![Screenshot (368)](https://user-images.githubusercontent.com/10144772/88080101-9a020c80-cb4c-11ea-81cc-886d17a2d76c.png)

**Comment by proggeramlug** [comment]
fixed!

**Comment by ggordn3r** [comment]
Confirmed! Closing.
