### ISSUE TITLE
Clicked "Publish Poll" and "OK" on validation, but poll state did not visibly change

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#133]
See screenshot. After clicking "Publish poll" and confirming the validation, nothing visibly changed on the page. When I refreshed, the page changed as expected: toggle to Open, Publish poll button gone, Vote on this Poll clickable and Promote Poll settings visible.

The expected behavior is that the page reflects the change automatically, with no need to refresh manually.

Here's the poll: https://rankit.skelpo.com/polls/o6OhlgVOkaxmcSDy5WB1
I actually clicked through "Publish poll" twice, so also acheck to make sure that doesn't mess anything up in the database.

![Screenshot (351)](https://user-images.githubusercontent.com/10144772/86314888-c7ffcb00-bbf6-11ea-914b-28498cd746db.png)

**Comment by proggeramlug** [comment]
Hmm, it seems like Google's database is fairly slow these days. I have not been able to reproduce this problem, can you try again? 

That being said: Google being slow might be part of such problems here.

**Comment by ggordn3r** [comment]
I tried again and see the same issue.

1) Clicked Create Poll to go to https://rankit.skelpo.com/polls/create
2) Entered title and choices
3) Clicked "Save Poll & Publish"
4) Got the dialog prompt: "Are you sure? Once you publish a poll others will be able to see it and vote on it until you close the poll." OK / Cancel
5) Clicked OK
6) Did not receive the expected validation message. URL did not change, even after minutes of waiting.

**Comment by proggeramlug** [comment]
Hmm, which browser, chrome? I just tested it and it worked well for me in FF. I'll check chrome as well.

**Comment by ggordn3r** [comment]
Chrome for me. Another user is reporting an issue where "the buttons don't work", which I think is another instance of this speed issue. I asked her for more info as well.

**Comment by proggeramlug** [comment]
Hm, I'm testing this and I'm fairly sure it is not related to creating a poll. It just worked as expected for me ... (new window).

Let's try to find it, but I don't think this is related to this particular bug.

**Comment by ggordn3r** [comment]
Ok, I'm going to leave this one open for a couple of days just to see if I encounter any other memory issues.
