### ISSUE TITLE
As an admin, I see a user's polls under his username in "manage users"

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#134]
Our FairVote point of contact says this was the standard behavior in the last release, so it may have been commented out or broken as a result of the addition of super users. Can you check?

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
While logged in as an admin, I tried the typical flow a few times ("Manage users" --> "See user polls" --> [Poll title]).

The first two steps worked as expected, but I did not succeed in viewing the poll management page on any of the 3 randomly chosen polls I tested:

Fail, doesn't load after 10 seconds - https://rankit.vote/polls/RugrX7FUcHRmmfF2zg7t
Fail, doesn't load after 10 seconds - https://rankit.vote/polls/Nblk3txg6jN7q5UvHRvw
Fail, doesn't load after 10 seconds - https://rankit.vote/polls/ryG2YoYQ1AaD59WS1BsA

As an aside, my testing was hampered by the time it takes to fetch users, so I've recommended #150.

**Comment by proggeramlug** [comment]
Sorry, you need to test this in the stage environment - Live does not have the updates yet and we would need to push all current changes.

**Comment by ggordn3r** [comment]
D'oh. I can't believe I made that rookie mistake. Just tested and it works great on staging. Closing!
