### ISSUE TITLE
Voting on mobile: align choices left and reduce width by 10%

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#138]
From a user:
_It’s hard to scroll on mobile without selecting candidates while you take a look at all of the choices. I think it’s because the choices extend to the edge pretty far. Can we narrow them or align them to the left so that a use can scroll on one side and view them all without accidentally selecting one?_

My recommendation:
On mobile, align choices left and reduce width by 10%. Also, make sure long choices wrap to new line.

**Comment by proggeramlug** [comment]
Done, can be tested!

**Comment by ggordn3r** [comment]
Much better! Closing.
