### ISSUE TITLE
Poll Summary: cosmetic changes

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#139]
Various small styling changes requested on /summary pages. See screenshot.

- Round the bottom left and right corners of the gray box containing the header
- Make the "Final Result" / "Round 1" header `h1` instead of `h2` on all result pages
- Reverse the emphasis on the two statements in the header (top is 'p' and bottom is 'h1')
- Deemphasize the sharing buttons by reducing their width and hiding them on Round Summary pages
- Change bottom button text on /summary only to "See Results by Round"

![Screenshot (362)](https://user-images.githubusercontent.com/10144772/87591962-1f05a580-c6b7-11ea-87f3-e60710b94cbb.png)

**Comment by proggeramlug** [comment]
Ready to be tested!

**Comment by ggordn3r** [comment]
Looks great!
