### ISSUE TITLE
Sort "My Polls" in reverse chronological order by creation date

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#144]
I created a new "Draft" poll and it appeared at the bottom of the list in "My Polls". Expected behavior is for new polls to appear in the first position, not the last.

![My Polls - RankIt](https://user-images.githubusercontent.com/10144772/88573302-848a5800-d00e-11ea-9ec6-cc3cd7cf5692.png)

**Comment by proggeramlug** [comment]
Fixed!
