### ISSUE TITLE
Prod: Round-by-round view broken in some polls

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#146]
I noticed that in both of these polls the Round-by-Round results view is totally broken:
https://rankit.vote/results/y644FmoM7b1T8lmAWAP4/1
https://rankit.vote/results/0s4l9EbBvhOY1PGgv3Ms/1

- Round counter on button does not advance, even though URL does
- Round Summary for each round is blank
- Graph is frozen in final results state

But the same polls when viewed on rankit.skelpo.com work correctly:
https://rankit.skelpo.com/results/y644FmoM7b1T8lmAWAP4/1
https://rankit.skelpo.com/results/0s4l9EbBvhOY1PGgv3Ms/1

These are older polls, so it could be that this is a legacy issue from before the last code push. No one has reported anything similar on newer polls. But I still think it's worth investigating, just to make sure there isn't a deeper issue that the next push needs to address.

**Comment by proggeramlug** [comment]
This is an issue that is currently live - it will be fixed once we push all this live.

**Comment by ggordn3r** [comment]
Ok, I will keep this in my column as a reminder to check after we push.
