### ISSUE TITLE
"Create Poll" buttons should be consistent between pages

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#147]
Compare the "Create Poll" button on https://rankit.skelpo.com/home with the one on https://rankit.skelpo.com/polls

- The one on /home should have a "+" icon, the same as the one on /polls
- The one on /polls should be the same size and alignment as the one on /home

**Comment by proggeramlug** [comment]
Fixed and adjusted!

**Comment by ggordn3r** [comment]
Very close--just needs to be centered on mobile on /polls. Compare screenshots below:

![Screenshot (390)](https://user-images.githubusercontent.com/10144772/88842047-dd8ff280-d1ac-11ea-9dcf-8ade1530b19f.png)
![Screenshot (389)](https://user-images.githubusercontent.com/10144772/88842048-de288900-d1ac-11ea-9855-3142971e35fc.png)

**Comment by proggeramlug** [comment]
Fixed!
