### ISSUE TITLE
Results: add threshold value as label to threshold line

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#149]
See screenshot. Users are not clear about the purpose of the threshold line. To make this more clear, add a label above it with the threshold value.

- Show as "T%" where T = threshold value
- Centered above threshold line
- Same size as Round Summary text
- Same color as the threshold line

![Screenshot (385)](https://user-images.githubusercontent.com/10144772/88601499-d4811300-d03e-11ea-879e-c34c8aaaa4d2.png)

**Comment by proggeramlug** [comment]
Implemented. The threshold is the total number for us (like 4). I'm calculating the % by dividing that number by the total vote count - is that correct?

**Comment by ggordn3r** [comment]
No, that's not quite right. The threshold as a % value is already stored exactly as we want it in the [explanation text](https://github.com/iambateman/RankIt/blob/master/src/app/results/components/explanation/explanation.component.ts) as:
`${this.percentToString(this.winning_percentage)}`

Can you just invoke that again for the label on the graph side?

**Comment by proggeramlug** [comment]
Fixed!
