### ISSUE TITLE
Searching "Manage polls" and "Manage users"

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#150]
For admins, fetching on the "manage users" and "manage polls" pages is now taking a very long time. This makes sense if they're loading all records--we now have over 4,000 registered users and probably something like 10,000 polls. It's also becoming increasingly difficult to find the exact user or poll you want to moderate and this will only get worse over time.

We need some way to help admins find the record they want more quickly. I propose:
- paginating both polls and users (50 on each page)
- sorting users descending by last login (i.e. the most recent logins appear on top)
- sorting polls descending by create datetime
- adding a search box to both pages for quick filtering to a known user or poll

**Comment by proggeramlug** [comment]
Okay, we have some limitations here: 

1. We cannot search for a title.
2. We cannot know how many polls/users we have in total.

Of course, we _can_ do both but that is a way different scope. Firebase's database is meant for documents, these kinds of operations are more relational (like SQL). There is no easy way to do both.

BUT what we can do:
1. Have a button "more" that loads the next 50
2. have a reset button that brings us back to the begininng.

Available for testing in stage - please test and let me know how to proceed.

**Comment by ggordn3r** [comment]
This looks good. I'll have to document how it works. What determines which user/poll shows up on page 1? Is it creation date? As I mentioned above, ideally the users with recent logins and polls with recent create dates are the first ones to appear, but I understand that's more of a SQL request.

**Comment by proggeramlug** [comment]
It's pretty random who shows up first. As this is not sortable by default we just know that we are getting them in order (presumably, but not guaranteed, in which they are created).

**Comment by ggordn3r** [comment]
Ok, I'll document this.
