### ISSUE TITLE
Feature: enable embedding polls

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#17]

**Comment by iambateman** [comment]
A first pass is available here: http://iambateman.com/blog/testing/

Thoughts?

**Comment by ggordn3r** [comment]
Update on this issue: The Nationbuilder iframe converter considers the embed code invalid, so Emily has been erasing some of it before clicking "convert". Emily will send a Quicktime video of her process here so we can troubleshoot.

**Comment by iambateman** [comment]
https://www.fairvote.org/iframe_converter << putting this here for ref

**Comment by iambateman** [comment]
[embed-code.txt](https://github.com/iambateman/RankIt/files/3700328/embed-code.txt)

Attached is an embed code specific to Fairvote.org that will make it look like this: https://www.fairvote.org/sb-test. I’m not sure how ya’ll are doing responsive, so I need some feedback on that. If you wish to embed a different poll, just switch the link.

**Comment by ggordn3r** [comment]
Fairvote is still problematic, as far as I know, but someone successfully embedded a poll in a Wordpress blog:
https://www.oregonhill.net/2019/10/16/rank-the-candidates-for-city-council-special-election/

**Comment by ggordn3r** [comment]
Emily is going to try embedding directly without putting it through iframe converter. No additional work on this until she gets back to us.
