### ISSUE TITLE
Feature: messaging for poll summary

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#18]

**Comment by iambateman** [comment]
Messaging doc: https://docs.google.com/document/d/1Sg1RXwpQY9KcvqS_AXgQu0-0Z6dZfDnqKh-T9MbI8rg/edit?ts=5d4a122f

**Comment by ggordn3r** [comment]
During testing, we've uncovered a need to review the multi-winner template language as well. @iambateman can you paste the templates for multi-winner in the Google Doc?

@oburbank we know the language so far does not address thresholds to win or surplus transfers. A tester suggested this language: "X candidate received more votes than they need to win. Their voters all have a portion of their vote go to the next candidate ranked on their ballot."

**Comment by oburbank** [comment]
lots of different round by round scenarios here. https://docs.google.com/document/d/1Sg1RXwpQY9KcvqS_AXgQu0-0Z6dZfDnqKh-T9MbI8rg/edit?ts=5d39b6c3#

**Comment by ggordn3r** [comment]
Later issues encompass this one. Hence, closing.
