### ISSUE TITLE
Need privacy policy

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#19]

**Comment by oburbank** [comment]
How about this one:
https://www.privacypolicytemplate.net/

**Comment by iambateman** [comment]
Because this has legal implications, I need your team to send me verbiage that you'd like me to put on the privacy policy.

Sorry to be weird about that, but it's got to be up to ya'll.

**Comment by oburbank** [comment]
https://app.termly.io/document/privacy-policy/2bab93f5-e82a-4c6b-95a9-7d3e0b67754b
