### ISSUE TITLE
 Nothing happens when you click the “create” poll button

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#21]
_from Trey: Could they be seeing the "create poll" button without being logged in?_

People experiencing the issue: Dave, Erica, Pam, Katie, Emily
Device: Mobile and desktop (Safari, Chrome, and Internet Explorer)

Taken from:
https://docs.google.com/document/d/1wMOpkNvZwIOV1eZ_m6w_cv4LqwT4AHzyelMAryYQrag/edit

**Comment by iambateman** [comment]
This is fixed.

It was a rules issue on my end. My bad.
