### ISSUE TITLE
3 winners, 2 blue bars

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#22]
In the multi-winner poll, the summary declares three winners (Warren, Buttigieg, and Harris) but in the visualization only two bars (Warren and Buttigieg) are colored blue

People seeing: Dave, Erica, Emily
Devices: Mobile and desktop (Safari, Chrome, and Internet Explorer

Screenshot in row 2 (sorry, I can't seem to download images from this file they created):
https://docs.google.com/document/d/1wMOpkNvZwIOV1eZ_m6w_cv4LqwT4AHzyelMAryYQrag/edit

**Comment by iambateman** [comment]
Duplicate of #43
