### ISSUE TITLE
All rounds are "round 1"

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#23]
'For both polls, when you click "see round 1," it (the button to click to the next round) still says round 1 after you run round 1. You can essentially run the rounds an infinite number of times, even after the election has ended'

Reporter: Pam
Device: Desktop/IE

_from Trey: The second sentence here may just be a misunderstanding, thinking that the results summary = tabulation. So I'm only considering the first sentence as the bug, but including the full comment for your reference._

**Comment by iambateman** [comment]
I'm 100% not sure what this means, but I'm pretty sure it's an IE issue.

**Comment by ggordn3r** [comment]
Yes, adding to wontfix.
