### ISSUE TITLE
Toggle to Featured Polls, 'no polls' message

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#27]
"It’s unclear where any polls are to vote in." ~ Katie, Desktop, Chrome

_from Trey: after login, a user can't return to the Featured Polls page. Can we add a home button in the top-left corner, or some kind of toggle between Featured Polls and My Polls? Also, after seeing the screenshot below, I think it makes sense to show a message when 'My Polls' is empty, like 'You haven't created any polls yet. Click the button above to get started.'_

See screeshot in row 7:
https://docs.google.com/document/d/1wMOpkNvZwIOV1eZ_m6w_cv4LqwT4AHzyelMAryYQrag/edit

**Comment by iambateman** [comment]
Yep, I added a back button.
