### ISSUE TITLE
Browser sniffing IE and posting a warning message

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#31]
Is it more than trivial to determine when someone navigates to the page in IE and post a warning message like 

> Unfortunately, RankIt does not support Internet Explorer. To ensure the app works for you, please use a different browser, like Chrome, Firefox, or Edge.

**Comment by iambateman** [comment]
It's certainly possible. Let's see if we get more errors from folks and address it then. I think it should be working better.

**Comment by ggordn3r** [comment]
We received no complaints about IE from beta testers, leading me to believe that this fix is now unnecessary. Hence, closing.
