### ISSUE TITLE
Edit access to issue tracker form

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#33]
Can you give me edit access to this form? I'm trying to add a place to upload screenshots before it goes out to beta testers tomorrow.

https://docs.google.com/forms/d/e/1FAIpQLSf4Tzg8zxbDrqKykbDGu97aeQAaET_tFit0sUzdb3vG9v-YVw/viewform

**Comment by iambateman** [comment]
yep. added you as a collaborator.
