### ISSUE TITLE
Polls do not auto-save

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#34]
_from Trey: Unsure if this is a bug or feature request. If it's a feature request, I'll switch to wontfix. Doesn't seem necessary when polls are so quick to make._

From Scott on Safari (mobile):

Created a new poll (without clicking Create Poll yet) with all the choices, etc. Then clicked the Account button in the top right. Clicking the back button brings me back to Create Poll screen and erases everything I created previously. (not sure if this is a bug or a function of not saving work)

**Comment by iambateman** [comment]
Hehe...this is a feature request. 

We're not going to be able to address this for this release.

**Comment by ggordn3r** [comment]
A beta tester managed to erase their poll by clicking out. Possible evidence for adding this feature.

> Clicking person icon in top right before clicking "Create Poll" totally wipes out the poll that I just finished creating! (I was just curious what that clickable spot was.)
> Craig Harvey
> caharvey@comcast.net

**Comment by ggordn3r** [comment]
Adding this as a new issue. Will reference this one for context. Another user requested some sort of save feature as well:

_I'm planning to use the rank it app for a poll at Manna for our costume contest and I realized that there is no way to save a poll if you're still editing the options. Is that in the roadmap for the app?_
