### ISSUE TITLE
"no candidate has over 25% of the vote", but graph shows 29%

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#35]
From Scott on Safari (mobile):
Results for multi-winner are confusing. Round Summary says no choice is over 25%, but bar graph says that candidate does have over 25% of the vote.

**See screenshot, row 10:** https://docs.google.com/document/d/1wMOpkNvZwIOV1eZ_m6w_cv4LqwT4AHzyelMAryYQrag/edit

**Comment by iambateman** [comment]
@oburbank and @ggordn3r  this is weird.
https://rankit-vote.appspot.com/results/HxP9Wblv4II1jRNg96gS/3

In this case, 
- the votes are `1, 2.8, 1.4, 5.2, 5.8, 6`
- threshold = 6.
- total active votes for third round = 22.2

Buttigieg's percentage = 5.8/22.2 = 26% of the vote. **But** Buttigieg has not reached the threshold of 6. How is it possible that he has received 26% of the vote, and still not won? More importantly: how should we display this? 


Full results below:
```
{ "elected": [ "Sen. Elizabeth Warren of Massachusetts", "South Bend, Indiana, Mayor Pete Buttigieg", "Sen. Kamala Harris of California" ], "rounds": [ { "Andrew Yang, entrepreneur": 1, "Former HUD Secretary Julián Castro": 2, "Former Vice President Joe Biden": 1, "Sen. Bernie Sanders of Vermont": 1, "Sen. Elizabeth Warren of Massachusetts": 10, "Sen. Kamala Harris of California": 4, "South Bend, Indiana, Mayor Pete Buttigieg": 4 }, { "Andrew Yang, entrepreneur": 1, "Former HUD Secretary Julián Castro": 2.8, "Former Vice President Joe Biden": 1, "Sen. Bernie Sanders of Vermont": 1.4, "Sen. Kamala Harris of California": 5.200000000000001, "South Bend, Indiana, Mayor Pete Buttigieg": 4.800000000000001 }, { "Andrew Yang, entrepreneur": 1, "Former HUD Secretary Julián Castro": 2.8, "Sen. Bernie Sanders of Vermont": 1.4, "Sen. Kamala Harris of California": 5.200000000000001, "South Bend, Indiana, Mayor Pete Buttigieg": 5.800000000000001 }, { "Former HUD Secretary Julián Castro": 3.8, "Sen. Bernie Sanders of Vermont": 1.4, "Sen. Kamala Harris of California": 5.200000000000001, "South Bend, Indiana, Mayor Pete Buttigieg": 5.800000000000001 }, { "Former HUD Secretary Julián Castro": 3.8, "Sen. Kamala Harris of California": 5.600000000000001, "South Bend, Indiana, Mayor Pete Buttigieg": 6.800000000000001 }, { "Former HUD Secretary Julián Castro": 3.964705882352941, "Sen. Kamala Harris of California": 6.235294117647062 } ], "threshold": 6 }
```

**Comment by oburbank** [comment]
5.8<6 is how.
The threshold is based the number of valid votes in the first round and doesn't get lowered when votes are exhausted in later rounds.

**Comment by oburbank** [comment]
you should be displaying percentages based on total votes, not current valid votes. Then have a disclaimer if they don't add up to 100.

**Comment by ggordn3r** [comment]
"you should be displaying percentages based on total votes, not current valid votes"

I suspect this distinction is the cause of several issues that have confused beta testers. In certain cases:
- Winners have been declared but have not been highlighted blue
- Winners have not been declared, despite apparently having met the threshold

Please update the formula and let's see if that resolves these issues.

**Comment by iambateman** [comment]
I believe this has been addressed by adding decimals and noting "Percentages may not add up to 100 because some ballots get all their choices eliminated."
