### ISSUE TITLE
Options already selected reappear, allowing user to rank same choice more than once

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#36]
From Dave on Chrome (desktop):

The buttons to choose options will spontaneously reorder themselves and options that have already been selected will reappear, allowing some choices to be ranked more than once.

See screenshots in row 13: https://docs.google.com/document/d/1wMOpkNvZwIOV1eZ_m6w_cv4LqwT4AHzyelMAryYQrag/edit

**Comment by iambateman** [comment]
@ggordn3r have you been able to reproduce? I haven't.

**Comment by ggordn3r** [comment]
I'm not able to reproduce either. I'm circling back with the tester who reported this for more information.

**Comment by ggordn3r** [comment]
The beta tester reattempted and has also been unable to reproduce. Apparently resolved by a new update, hence closing.

**Comment by ggordn3r** [comment]
This bug has come back with a vengeance. On the first night of the Democratic primary soft launch, we had at least 4 reports of this bug. I'm including some screenshots below.

Is it possible that this is connected to people voting simultaneously? Could two users trying to vote at once or the results reloading cause choices to repopulate?

**Comment by iambateman** [comment]
Figured it out. This was a problem with the observable. When someone else voted, it refreshed everything and pushed it out to everyone. Hence the new choices (and why it never came up for us).

This is fixed.
