### ISSUE TITLE
Single-winner poll highlights two winners (possible tie?)

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#37]
From Jeremy on Chrome:

It’s not clear to me why Yang wins here, since the results appear to a tie. It could be worth explaining if Yang wins by a random drawer or if he actually has one more vote or something. When I went to round-by-round results, the explanation in round 4 is even more confusing, since it says both Yang and Warren are eliminated but then says “We have a winner!” 

See screenshots in row 14: https://docs.google.com/document/d/1wMOpkNvZwIOV1eZ_m6w_cv4LqwT4AHzyelMAryYQrag/edit

_from Trey: I'm surprised that a tie would occur with 59 votes in, but I suppose it's possible. Is there any way to tell? If it is a tie, we should assign oburbank to add language explaining the "tie" case as a coin flip. Either way, it shouldn't be highlighting both candidates._

**Comment by iambateman** [comment]
There is now "tie" language that should address this situation. Please confirm & close.

**Comment by oburbank** [comment]
is that language live yet? I'm not seeing it.

**Comment by iambateman** [comment]
yep! https://rankit-vote.appspot.com/results/buddysB1xPIWJJJC5nFR/summary

**Comment by ggordn3r** [comment]
Confirmed--I am seeing the tie language in the provided example. Hence, closing. @oburbank if you don't see it on that link, please reopen.
