### ISSUE TITLE
If a choice is blank, you should just delete that choice and create the poll

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#4]
https://www.dropbox.com/s/im4n5bzglw98ysx/Screenshot%202019-08-17%2008.51.41.jpg?dl=0

**Comment by iambateman** [comment]
@oburbank I see what you mean. On the other side, if someone purposefully adds four choices, but doesn't fill them all in, could it be helpful to alert them?

Just talking it out.

**Comment by ggordn3r** [comment]
@iambateman I think validation is a good idea.

**Comment by iambateman** [comment]
Validation is added! Please confirm and close.

**Comment by ggordn3r** [comment]
Clicking "add choice" without clicking into the box doesn't show the validation message. 

"There are errors that need to be fixed above before this poll can be created." does appear at the bottom, but the error itself isn't shown, even if you click "Create poll."

Not a huge deal, but a little confusing. See screenshot. Is there an easy way to improve this? For example, display all error messages if someone clicks "create poll"?

![Create Poll - RankIt](https://user-images.githubusercontent.com/10144772/71201705-9762d000-2268-11ea-8856-cadb2c1bd164.png)

**Comment by ggordn3r** [comment]
I managed to break this:
1) Create 3 choices
2) Set Winners to 2
3) Delete a choice (Note: Winners appears to be blank but is actually still set to previous value)
4) Click "create poll"

The result is a 2 winner poll with 2 choices. Not a huge deal, but worth fixing I think.

URL to the poll I created: https://rankit.vote/polls/swl6SAuzCHIvh17ty7eL
