### ISSUE TITLE
Why isn't the bar chart proportional?

### ISSUE THREAD

**Issue by oburbank** [iambateman/RankIt#41]
![image](https://user-images.githubusercontent.com/1431739/65694783-69446a00-e044-11e9-9fb9-0c1ea934cfbe.png)

the 40% bar should be twice as long as the 20% bar

**Comment by iambateman** [comment]
Good question.
- the 'line to gain' is 25% (assuming this is a three winner poll).
- 20/25 = 80%, which is the length of the 20% bar.
- 40/25 = 160%, which is truncated in order to keep it from throwing things way off.

**Comment by oburbank** [comment]
ok, in v2 we should have the chart scale to the largest bars, or at least have a better indicator that the 40% bars continue past the scope of the visible chart.
