### ISSUE TITLE
Limit number of winners to number of candidates - 1

### ISSUE THREAD

**Issue by oburbank** [iambateman/RankIt#42]

**Comment by ggordn3r** [comment]
@oburbank This works for me--the drop-down for "Winners" adjusts to the number of choices. Are you seeing something different? If so, please share a screenshot.

**Comment by oburbank** [comment]
Yes. It's currently set to number of candidates:
![image](https://user-images.githubusercontent.com/1431739/65723989-7c276080-e07d-11e9-9bdd-8080e1ac5509.png)

I want it to be 1 less than the number of candidates

**Comment by iambateman** [comment]
I believe this left at (N-0) because it's theoretically possible that someone would want to use RankIt to determine an ordering, without necessarily a specific winner.

At least that's what I recall from conversations a while ago. Is this not a valid use case/

**Comment by oburbank** [comment]
That isn't a valid use case. And if it was, a single winner rcv would be the best approach.

**Comment by ggordn3r** [comment]
@iambateman FYI, a beta tester also showed a preference for N-1:

> I was able to create a poll with 8 choices and 8 winners. This seems like a somewhat farcical and non-informative election to run, if I do say so myself. Either some of the choices get no votes, and are eliminated in round 1 (leaving some seats unfilled), or there are 8 winners out of 8 options.
> 
> I guess this is a sort of subjective thing, but I don't know if this should be possible in the web app.
> 
> To create this poll, I added 8 choices, then selected the number of winners from the "winners" drop-down. It allowed me to select up to 8 winners, and so I did.
> https://rankit-vote.appspot.com/polls/hKTSBfGroU4eqb4j1m3s
> dandromb@gmail.com

**Comment by ggordn3r** [comment]
Another beta tester was confused about the limit tied to the number of choices. Perhaps we should add an extra sentence to the tooltip: "The maximum number of winners is the number of choices you add minus one."

> Surely you can have more than 3 winners, right?
> Sawyer Morgan
> sawyer.morgan8@gmail.com

![Screen Shot 2019-10-09 at 7 01 57 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66775070-31855100-ee91-11e9-925a-fe4fc344b9ef.png)

**Comment by iambateman** [comment]
This is done!

**Comment by ggordn3r** [comment]
I managed to break this:

1) Create 3 choices
2) Set Winners to 2
3) Delete a choice (Note: Winners appears to be blank but is actually still set to previous value)
4) Click "create poll"

The result is a 2 winner poll with 2 choices. Not a huge deal, but worth fixing I think.

URL to the poll I created: https://rankit.vote/polls/swl6SAuzCHIvh17ty7eL

**Comment by iambateman** [comment]
Ah yes. Thanks for fixing this, it's good to go.
