### ISSUE TITLE
It's possible that a winner from a multi-winner contest doesn't reach the threshold

### ISSUE THREAD

**Issue by oburbank** [iambateman/RankIt#43]
When this happens the candidate's bar should still be blue, currently its not:
![image](https://user-images.githubusercontent.com/1431739/65695840-41ee9c80-e046-11e9-9be9-a9887ebbde7c.png)

**Comment by oburbank** [comment]
When this happens, in the last round every candidate that won should be mentioned as winning even if they did not receive the threshold. Currently this does not happen:
![image](https://user-images.githubusercontent.com/1431739/65696344-0f916f00-e047-11e9-95ff-0f4af4207e59.png)

**Comment by iambateman** [comment]
I believe this is resolved:
https://www.dropbox.com/s/sga5q2xqjur2px4/Screenshot%202019-10-07%2021.31.56.jpg?dl=0

Please retest and Let me know.

**Comment by oburbank** [comment]
looks good.
