### ISSUE TITLE
Double-quotes in the CTA label breaks poll creation

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#44]
First observed on https://rankit-vote.appspot.com/vote/OwsY3ZXNtsp29KANXhYG

**Comment by iambateman** [comment]
I just tried to test this by putting quotes in the cta label and it worked fine. Can you try again?

**Comment by ggordn3r** [comment]
I did my very best to recreate this, but alas, I could not (Enjoy some quality entertainment here: https://rankit-vote.appspot.com/vote/tK2kARMjJSnyYoFpLKnS). 

Perhaps this was actually a duplicate of Owen's issue creating polls. Closing.
