### ISSUE TITLE
As an admin, I can export email addresses to CSV from within RankIt

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#46]
(with the idea to import them into my mail handler of choice... Nationbuilder, Constant Contact, etc.)

Alternatively, push email addresses collected to Nationbuilder via API:
API documentation:
https://nationbuilder.com/api_quickstart

Contacts --> POST allows you to create a contact from JSON

**Comment by proggeramlug** [comment]
Implemented, check it out!

**Comment by ggordn3r** [comment]
Looks good. 2 small requests:
1) Can you use the purple button style on the poll creation page for this button?
2) Can you make the label read "Download email addresses (CSV)"?

**Comment by proggeramlug** [comment]
Done!
