### ISSUE TITLE
I can't create a poll

### ISSUE THREAD

**Issue by oburbank** [iambateman/RankIt#49]
I logged on with facebook. I've filled out all required fields, but I get "There are errors that need to be fixed above before this poll can be created." at the bottom of my screen:

![image](https://user-images.githubusercontent.com/1431739/65723426-606f8a80-e07c-11e9-930c-4d0fe3201a2d.png)

I'm on appspot

**Comment by oburbank** [comment]
I can create a poll when I login with google, perhaps this is specifically a facebook problem>

**Comment by oburbank** [comment]
It actually seems like the problem only occurs when you have 3 or more candidates. You can create a poll with 2 candidates but not 3 at the moment.

**Comment by iambateman** [comment]
If this happens again, can you screenshot the JS console and send it to me? I've tested both FB and 3+ candidates, and both are working for me. Sorry, having trouble reproducing.

**Comment by oburbank** [comment]
![bug](https://user-images.githubusercontent.com/1431739/66080789-cc4a6b00-e534-11e9-88c7-d0b7ce60a2a7.gif)

**Comment by iambateman** [comment]
I believe this is resolved: https://rankit-vote.appspot.com/polls/create
