### ISSUE TITLE
Replace home page lorem ipsum with real video and text

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#50]
**Youtube link to video for embed**: https://www.youtube.com/watch?v=Rgo-eJ-D__s 

**Text for the front page just below the video:**

Ranked choice voting (RCV) makes democracy more fair and functional. It works in a variety of contexts. 

With RCV, voters have more options and power by ranking as many candidates as they want in order of choice on their ballot. Candidates do best when they attract a strong core of first-choice support while also reaching out for second and even third choices. 

Learn more by visiting www.FairVote.org.

**Comment by iambateman** [comment]
This is done. We need to document that it's editable in Firebase database, under "admin / settings"
