### ISSUE TITLE
Replace text under "Final Result" with first line of Poll Summary

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#52]
Sorry about this--I wasn't clear enough in the Rankit Language page about where they wanted the first line to go. The line under Final Results, "10 votes in 2 rounds to elect 3 choices", should be replaced with "After 2 rounds and 10 votes, Nick Chubb and Kareem Hunt win." It should not be under the Poll Summary, as it is now.

See screenshot:

![Screenshot (70)_LI](https://user-images.githubusercontent.com/10144772/66519342-214a2c00-eab5-11e9-8380-5ac01b1bee22.jpg)

**Comment by ggordn3r** [comment]
A user also complained about this in testing:

> Watch the plural! "19 votes in 6 rounds to elect 1 choices." should of course be "choice" here. This also is not a complete sentence and doesn't need a period. Furthermore, the syntax of this doesn't make the most sense; could be something like "19 votes to elect 1 choice in 6 rounds" or "19 votes were cast and 1 choice was elected after 6 rounds." The votes are not cast in rounds, but are counted in rounds.
> https://rankit-vote.appspot.com/results/ZuYnmedVyAbD4CeWU5cH/summary
> Sawyer Morgan
> sawyer.morgan8@gmail.com

**Comment by iambateman** [comment]
This is done! They now mirror one another.
