### ISSUE TITLE
Excess votes are not visibly redistributed

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#53]
In the following 2-winner poll, votes above the threshold are visibly taken away from the first winner, but not visibly added anywhere else. (Toggle between Round 1 and 2 to see this in action)

https://rankit-vote.appspot.com/results/851Y5u7LoRXSNT7R4Nj4/summary

Here's the original bug report in full:

> From: Kirk Earl <kirk@democracymaine.org>
> 
> I'm finding the multi-winner ranked-choice voting poll rather confusing. In the 2-winner poll I made, one of the options has more than 33% of the vote in the first round, so the prompt says the excess votes are reallocated to their second choices. However, the percentages of the other options don't change after this reallocation, and the numbers don't add up to 100% anymore even though I had every "vote" list every option. Is this what's supposed to be happening?
> 
> Here's the results summary from my test if anyone wants to look: https://rankit-vote.appspot.com/results/851Y5u7LoRXSNT7R4Nj4/summary

**Comment by iambateman** [comment]
```
{ "elected": [ "Chocolate cake", "Homemade ice cream" ], "rounds": [ { "Apple pie": 1, "Brownies": 2, "Chocolate cake": 5, "Homemade ice cream": 3, "Pumpkin pie": 1 }, { "Apple pie": 1, "Brownies": 2, "Homemade ice cream": 3, "Pumpkin pie": 1 }, { "Apple pie": 2, "Brownies": 2, "Homemade ice cream": 3 }, { "Brownies": 2, "Homemade ice cream": 5 } ], "threshold": 5 }
```

I'm not totally sure why, but the algorithm is calculating that Chocolate Cake's leftover votes need to go into the ether. It's possible that they're both being exhausted I think. 

https://rankit-vote.appspot.com/results/oKRt07pvGJ9BMefkUkFs/summary
is an example of redistributing votes happening.

**Comment by ggordn3r** [comment]
Ok, thanks for checking. Before I close this, can you also check the poll below (also mentioned in #76 )? The beta tester specifically mentions that each vote ranked all possible colors, so there's no chance of them being exhausted:

https://rankit-vote.appspot.com/results/JrM4uglKcUOe6tywgXwJ/2

**Comment by iambateman** [comment]
I checked on it, and basically it looks like a problem of not enough votes in the poll. I added some more votes to that specific poll and it's working fine, as far as I can tell.
