### ISSUE TITLE
"There are errors that need to be fixed above before this poll can be created"

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#55]
Error message appears, but there is no validation on whichever field is the problem. From the screenshots, it could be a character issue related to #44, which we were unable to reproduce.

Original bug report in full:

> It says that there are errors that need to be addressed, but doesn't say what they are and I can't figure it out.

> Sam Bonar
> samjaredb@gmail.com

![Screen Shot 2019-10-09 at 1 48 02 PM - Sam Jared Bonar](https://user-images.githubusercontent.com/10144772/66705326-fea55680-ecf2-11e9-803f-7f143c35f903.png)

![Screen Shot 2019-10-09 at 1 47 53 PM - Sam Jared Bonar](https://user-images.githubusercontent.com/10144772/66705332-1086f980-ecf3-11e9-9dc7-0417792e978d.png)

**Comment by ggordn3r** [comment]
Ah, I see a blank choice in her screenshot, making this a duplicate of #4. If you add a more specific validation message, e.g. "One or more of your choices above were left blank. Please fill out or delete blank choices to continue."

**Comment by iambateman** [comment]
It now throws an error on the specific element saying 'choices cannot be left blank.'
