### ISSUE TITLE
In polls with many choices, scrolling is difficult on mobile

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#56]
Multiple users report that in polls with many options on mobile, they can't scroll to the bottom choices without "tapping" the top ones. Perhaps we should add some space on either side of the choice boxes? (Also open to other solutions)

First report:
> Scrolling down to see all the choices is hard because swiping up ends up moving a choice instead.
> URL: https://rankit-vote.appspot.com/vote/oKRt07pvGJ9BMefkUkFs
> Boris Kofman
> bkofman@gmail.com

Second report:
> Longer lists are difficult to navigate on mobile devices because of the inability to scroll up and down without moving the choices
> Michael Patison
> jmpatison@gmail.com

**Comment by iambateman** [comment]
Doh. we did this a long time ago and I didn't mark it closed. Please confirm on mobile and close, but I believe we're good.
