### ISSUE TITLE
"View results" persists as white box

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#58]
See screenshot.

> On the final page after going through the results, there's still an immovable box at the bottom of the page that does not scroll with you, but it's just white instead of the previous "Show Results" or the round number.
> https://rankit-vote.appspot.com/results/share/ZuYnmedVyAbD4CeWU5cH
> Sawyer Morgan
> sawyer.morgan8@gmail.com

![Screen Shot 2019-10-09 at 6 44 28 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66705540-29dd7500-ecf6-11e9-8624-dba5a47158a3.png)

**Comment by iambateman** [comment]
This should be fixed!
