### ISSUE TITLE
Prevent choices from "swapping sides" during reordering

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#59]
I think this is a keen observation--I've also noticed that it's easy to become disoriented when selecting from long lists due to the automatic reordering. But now that he mentions it, I bet it wouldn't be so disorienting if the choices didn't move back and forth between columns.

Can you try making it so choices only move vertically, not horizontally? In other words, that they never "swap sides"?

> When you select a candidate from the list, all the remaining candidates reorganize themselves to fill the missing space. This means I have to look through it again to find what I was looking for because they've swapped sides!
> https://rankit-vote.appspot.com/vote/oKRt07pvGJ9BMefkUkFs
> Sawyer Morgan
> sawyer.morgan8@gmail.com

![Screen Shot 2019-10-09 at 6 48 19 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66705635-43cb8780-ecf7-11e9-84c6-f88c613fe061.png)

![Screen Shot 2019-10-09 at 6 48 27 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66705638-46c67800-ecf7-11e9-8a05-da13749d58bd.png)

**Comment by ggordn3r** [comment]
This is also implicated in another report from a tester.  Because all other choices move out of the way when you drag one, you can hold a choice in a certain position and cause the others to "flicker" as they rapidly move around the screen.

**Comment by iambateman** [comment]
This was fixed by removing the two-column layout on mobile: https://www.dropbox.com/s/2kmvmtuqu0di4ho/Screenshot%202019-12-08%2012.41.10.jpg?dl=0

We good to close this?

**Comment by iambateman** [comment]
This was fixed by removing the two-column layout on mobile: https://www.dropbox.com/s/2kmvmtuqu0di4ho/Screenshot%202019-12-08%2012.41.10.jpg?dl=0

We good to close this?
