### ISSUE TITLE
Drag & Drop: transparent box appears when dragging choice

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#6]
https://www.dropbox.com/s/gbo2rhn1obad0yj/Screenshot%202019-08-17%2008.54.33.jpg?dl=0

**Comment by iambateman** [comment]
This isn't happening for me anymore. Please confirm and close!

**Comment by oburbank** [comment]
this is still happening for me

**Comment by iambateman** [comment]
Are you using http://rankit-vote.appspot.com/home ?

**Comment by oburbank** [comment]
![image](https://user-images.githubusercontent.com/1431739/65725585-0c1ad980-e081-11e9-856d-87f23b39664d.png)

**Comment by iambateman** [comment]
I'm pretty sure this is resolved.

**Comment by iambateman** [comment]
Closing, this is resolved!
