### ISSUE TITLE
Replace text with hyperlink in tooltip

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#61]
On the "Create Poll" page, under the Winners (?) tooltipl, we should link to the following URL instead of a static "FairVote.org":
https://www.fairvote.org/multi_winner_rcv_example

> Winners (?): The info box when I click this needs to link to the exact page, not "Fairvote.org" without even a hyperlink! 
> https://rankit-vote.appspot.com/polls/create
> Sawyer Morgan
> sawyer.morgan8@gmail.com

![Screen Shot 2019-10-09 at 6 58 30 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66705755-dc163c00-ecf8-11e9-9247-ae79564173f6.png)

**Comment by iambateman** [comment]
This is done!
