### ISSUE TITLE
On create poll page, let "tab" also move cursor to new choice

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#62]
Did you even know that "Tab" did this? I didn't. If this is likely to be complicated, switch to the backlog.

> Hitting tab when adding choices opens up a new blank choice (nice feature), but doesn't put the cursor there.  Either put the cursor in the new blank box or don't have Tab create a new blank box. 
> https://rankit-vote.appspot.com/polls/create
> Craig Harvey
> caharvey@comcast.net

**Comment by ggordn3r** [comment]
FYI, another tester produced this same outcome with a different input:

> when I shift-alt-tab from a blank option to a previous option, the app creates a second blank option
> https://rankit-vote.appspot.com/polls/create
> grant oxer
> grant.oxer@gmail.com

**Comment by proggeramlug** [comment]
This should have been fixed already.
