### ISSUE TITLE
URL with invalid round number shows a blank results page

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#65]
Oooh, I think this guy wins my "best bug" award:

> Users can manually type (and share) a URL with an invalid round number at the end, to show a blank results page.
> https://rankit-vote.appspot.com/results/sTsnPwNkivusmR8j9Noe/7
> dandromb@gmail.com

![Screenshot_2019-10-10 Results - pizza toppings - RankIt - Daniel Dromboski](https://user-images.githubusercontent.com/10144772/66706090-dc183b00-ecfc-11e9-8a22-966f1762bcc9.png)

**Comment by iambateman** [comment]
This is wonderful. It now redirects to the summary

**Comment by ggordn3r** [comment]
Hmm... doesn't seem to work for me. See screenshot.

![Screenshot (103)](https://user-images.githubusercontent.com/10144772/67414950-0a660800-f592-11e9-80b3-54ace269e85c.png)

**Comment by iambateman** [comment]
This should be fixed once some stuff propagates tomorrow.
