### ISSUE TITLE
Widen layout on desktop

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#66]
Several beta testers commented on the design feeling cramped on desktop, so Stephen has designed a new two-column layout for desktop. See attached mockups for how each screen should look. The only screen missing is the vote screen (still in progress).

**A few notes from Stephen**
- this is 1200px wide.
- create poll page changes nothing, except maximum width
- I added some navigation on desktop. In my mind, the back button goes away on mobile, and is replaced by a hamburger nav.
- the home page adds ‘my recent polls’ which is just the three newest polls from a user. (See #114--this has been added to 2.0 for June 30 but not the priority release)
- in most cases, the desktop adjustment is to add two columns.

Home page:
![Desktop – home (1)](https://user-images.githubusercontent.com/10144772/80378635-f2d24980-886a-11ea-8a44-2322567186fe.png)

Poll overview:
![Desktop – poll-overview](https://user-images.githubusercontent.com/10144772/80378661-fa91ee00-886a-11ea-9140-ce33677832b1.png)

Results:
![Desktop – results](https://user-images.githubusercontent.com/10144772/80378676-041b5600-886b-11ea-8018-b680f9a01a6f.png)

Round 1:
![Desktop – round 1](https://user-images.githubusercontent.com/10144772/80378694-08e00a00-886b-11ea-8352-d866512528f6.png)

Success:
![Desktop – success!](https://user-images.githubusercontent.com/10144772/80378702-0d0c2780-886b-11ea-8a4a-00c6e93f1f50.png)

**Comment by iambateman** [comment]
This is a cool idea, and should be considered for a phase 2.

**Comment by ggordn3r** [comment]
In broad strokes, I'm thinking the new layout would split the current layout in half and show it in two columns. Column 1 (left) would be the title and graph. Column 2 (right) would be the round summary and sharing links. The header with the RankIt logo and the footer with the buttons would extend across both columns.

**Comment by ggordn3r** [comment]
My last comment was for the results page, this one pertains to voting.

For voting, we should again have two columns. The left column would show all choices:
- fixed width
- icon indicating ability to drag/drop
- cursor changes to drag/drop on hover

The right column would be a larger version of the existing dotted space for ranking.

The inspiration for this approach comes from YouGov, which naturally has changed its URL scheme completely since someone shared it. I capture a screenshot in this Google Doc, though, which we can still use for reference:
https://docs.google.com/document/d/19BjjqOb6uggo8ene0GyCY0QJoSoKiedUmk0lEi6XOko/edit?ts=5e16883c

**Comment by ggordn3r** [comment]
@iambateman leaving this assigned to you for design specifications. Once you've defined those, reassign to Ralph and move the card to his column on [the project board](https://github.com/iambateman/RankIt/projects/1).

**Comment by proggeramlug** [comment]
@ggordn3r ready to test! please test in all browsers you know. 

I have hardly tested myself except for firefox, so don't blow up on me if something is off but it's also not too big of a change really .. ;)

**Comment by ggordn3r** [comment]
Worked great in Chrome, immediately dies in Edge. :D

If you're curious, here's the console log when I go from /home to /auth/login:

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
scripts.2defe9b2961799dbe6ef.js (1,292)

ERROR Error: Uncaught (in promise): TypeError: Unable to get property 'unsubscribe' of undefined or null reference TypeError: Unable to get property 'unsubscribe' of undefined or null reference at t.prototype.ngOnDestroy (https://rankit.skelpo.com/12.9fb3f5983376e4af183c.js:1:3973) at Anonymous function (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:1020864) at Vi (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:1020743) at Anonymous function (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:1020571) at Mi (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:1020360) at t.prototype.destroy (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:1024427) at e.prototype.destroy (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:1071808) at t.prototype.deactivate (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:481799) at t.prototype.deactivateRouteAndOutlet (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:437311) at t.prototype.deactivateRouteAndItsChildren (https://rankit.skelpo.com/main.99e117e51c4c7c32759a.js:1:436882)
```

**Comment by ggordn3r** [comment]
@proggeramlug Assuming you don't want to tackle Edge (see above), comment to let me know and I'll close the issue.

**Comment by proggeramlug** [comment]
@ggordn3r 

1. I'm so glad edge runs on macOS as well. :)
2. I'm more glad edge is really pretty much chrome
3. the problem is fixed, it runs well for me now ;D

**Comment by ggordn3r** [comment]
Haha that is good news indeed. Just rechecked in Edge, working very smoothly!
