### ISSUE TITLE
Bar of final winner is shorter than other winners

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#67]
Compare "broccoli" to the other winners in screenshot. Not only is it shorter than the others, but it doesn't even visibly clear the threshold. This may be related to #35. 

> Non-even sizes of winner bars in bar chart, after some winners have redistributed their excess votes, and whereas the final winner only just barely made it to the threshold.
> https://rankit-vote.appspot.com/results/x9BtuJNjBrv3WO3Zk3F1/7
> dandromb@gmail.com

![Screenshot_2019-10-10 Results - pizza a third time - RankIt - Daniel Dromboski](https://user-images.githubusercontent.com/10144772/66706308-fc48f980-ecfe-11e9-8c80-ed6e6cc6da05.png)

**Comment by iambateman** [comment]
This is a problem of inherent to RCV with small numbers of votes.

```
{ "elected": [ "pineapple", "asparagus", "tomato slices", "broccoli" ], "rounds": [ { "asparagus": 4, "bacon": 2, "broccoli": 4, "chicken": 3, "feta cheese": 2, "onion": 1, "pineapple": 3, "tomato slices": 4 }, { "asparagus": 4, "bacon": 2, "broccoli": 4, "chicken": 3, "feta cheese": 2, "pineapple": 4, "tomato slices": 4 }, { "asparagus": 5, "broccoli": 4, "chicken": 3, "feta cheese": 2, "pineapple": 5, "tomato slices": 4 }, { "asparagus": 5, "broccoli": 4, "chicken": 3, "feta cheese": 2, "tomato slices": 4 }, { "broccoli": 4, "chicken": 3, "feta cheese": 2, "tomato slices": 4 }, { "broccoli": 4, "chicken": 3, "tomato slices": 6 }, { "broccoli": 4.500000000000001, "chicken": 3.4999999999999996 } ], "threshold": 5 }
```

The underlying data is above. We need to get to 5 to win, unless it's the last one. We've reduced all the others to exactly 20%. Broccoli has 4.

I switched it to show one decimal point, which should help: https://www.dropbox.com/s/oxi1u795bcp4t4q/Screenshot%202019-11-16%2011.26.41.jpg?dl=0

**Comment by ggordn3r** [comment]
I see. So the real issue is that the last winner _doesn't_ actually have to get 20% to win, because the seat must be filled. Am I understanding that right?

If so, this is an edge case that we need to kick back to FairVote for new copy.

**Comment by iambateman** [comment]
I changed this to read 'In a multi-winner ranked choice voting poll with 4 winners, each winner must get at least 20% of the vote **or be the last choice standing**.'

In addition, we added a decimal point, which prevents it from falsely rounding up.
