### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#68]
Perhaps this could be a solution to #65 as well.

> blank-looking page when the user types a URL that has the correct domain name (rankit-vote.appspot.com), but an invalid subpage after the slash.
> 
> Might expect a "page not found" message, or a 404 error, etc. Non-technical users might be confused by this blank page, I suppose.
> https://rankit-vote.appspot.com/thissubpagedoesnotexist
> dandromb@gmail.com

![Screenshot_2019-10-10 Rankit - Daniel Dromboski](https://user-images.githubusercontent.com/10144772/66706360-74172400-ecff-11e9-89c3-0b1c05578db9.png)

**Comment by ggordn3r** [comment]
Would a redirect to home be easier?

**Comment by iambateman** [comment]
404 is added! Try adding random characters and you should see it redirect to `/home/not-found`

**Comment by ggordn3r** [comment]
Uh-oh... clicking the sign-up button on the home page also points to https://rankit.vote/home/not-found. Can you fix that?

**Comment by iambateman** [comment]
This is fixed!
