### ISSUE TITLE
Voting reordering

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#7]
You should be able to delete any choice, not just your last choice. The minus sign is inconsistent with other “delete this” icons in our app. All icons that do the same thing should look alike.

**Comment by iambateman** [comment]
[Preview](https://www.dropbox.com/s/erjgjpvtz2h1rq3/Screenshot%202019-08-17%2008.56.06.jpg?dl=0)

**Comment by iambateman** [comment]
@oburbank This one is tougher to get right than I expected.

- Someone in first position cannot move up, and thus ought not have an up arrow
- Someone in last position cannot move down, and thus ought not have a down arrow
- Putting three buttons in a row makes it difficult to tap on a phone, given the available space.

I thought this solution was clever, but I'll rework it.

**Comment by iambateman** [comment]
I've switched this so all three buttons always appear, but only sometimes do things.

**Comment by oburbank** [comment]
now horizontal this time!

**Comment by iambateman** [comment]
I made them a lot smaller. Could you take a look and Let me know what you think.

**Comment by iambateman** [comment]
Closing per conversation with Emily.
