### ISSUE TITLE
Add feedback email address

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#71]
The email address for app feedback and bug reports is rankit@fairvote.org. Somewhere conspicuous enough, we should add a message like this:

"Problems with the app? Email rankit@fairvote.org."

Not sure where exactly... footer? Account menu?

**Comment by iambateman** [comment]
This is done. It doesn't really work to put on every page (esp not voting), but I put it on the home page.

**Comment by ggordn3r** [comment]
I'm seeing it on several pages in the footer, including the account menu, so this looks good to me.
