### ISSUE TITLE
3rd winner is not highlighted

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#73]
I suspect this may be related to #35. If the underlying calculations are working off of two different "totals" (with vs. without exhausted votes) then numbers will get weird in later rounds, and the rules that run off of those numbers may not fire.

Unfortunately, this was tested on the featured poll, which has since seen more votes:
https://rankit-vote.appspot.com/results/oKRt07pvGJ9BMefkUkFs/summary

But take a look at the screenshot and try to replicate.

> Immediately after clicking Show Results it goes to the Final Result, but although there are three winners, only two are highlighted here – Hiking is still gray.
> Sawyer Morgan
> sawyer.morgan8@gmail.com

![Screen Shot 2019-10-09 at 6 53 28 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66774522-c1c29680-ee8f-11e9-9842-c0858ca04322.png)

![Screen Shot 2019-10-09 at 6 53 20 PM - Sawyer Morgan](https://user-images.githubusercontent.com/10144772/66774526-c424f080-ee8f-11e9-9d0f-8af337e87b89.png)

**Comment by ggordn3r** [comment]
Another beta tester confirms this issue:

> Leaves changing color wasn't highlighted, yet it was a winner. Especially weird since it and cool weather both show as 25 (even though this is a rounding thing).
> Aaron "RCV Pizza Card" Fowles
> aaron@rankedchoicetn.org

**Comment by iambateman** [comment]
sometimes all it takes is `|| round == 0`. This is fixed.
