### ISSUE TITLE
Choices with equal, low percentages are all mentioned for elimination in summary

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#75]
Read the round summaries carefully for this poll:
https://rankit-vote.appspot.com/results/ZuYnmedVyAbD4CeWU5cH/4

Even though only one candidate is eliminated in each round, all candidates with equal values are mentioned as being eliminated "one at a time." Unfortunately, because the totals continue to update, that doesn't reliably happen:

Round 3: "Booker, Bullock, Delaney, and Yang, will be eliminated one at a time" 
(all have 4%)
Round 4: "Bullock and Delaney, will be eliminated one at a time" 
(One of Booker's votes was reallocated to Yang, putting him at 6% and saving him from elimination)
Round 5: "Bullock and Yang, will be eliminated one at a time"
(One of Delaney's votes was reallocated to Bullock, tying him up with Yang at 6%)

Addressing this properly probably either means 1) adding my commentary above as additional explanation in the round summary or 2) switching to batch elimination. Either way, this is something for the backlog, but it will definitely come up again in polls with many minority choices.

Here's the original report of the beta tester who noticed this: 

> The explanation at the bottom should say which candidates are being eliminated in the round.  It doesn't consistently do this.  It gave four candidates to be eliminated.  In the next round, it had eliminated one and then listed two candidates to be eliminated. 
> Paul, paulcamann@gmail.com

**Comment by iambateman** [comment]
To add to this: the nature of the algorithm is that it removes the lowest choice, and randomly selects one in the event of a tie. I suppose we could 'look ahead' to determine in which order the choices will be removed.

But in any given round, it is correct (and clear) to say `Booker, Bullock, Delaney and Yang will be eliminated one at a time`. Then once Bullock is removed, to say `Booker, Delaney, and Yang will be eliminated one at a time`. 

In my opinion, it is confusing to just say `Booker will be eliminated`, when they're tied and all being eliminated.
