### ISSUE TITLE
Sort bars in descending order

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#77]
A beta tester recommended that the results should be in descending order by % of vote. In other words, the largest vote-getters always appear in the top position, and the eliminated parties at the bottom.

**Comment by iambateman** [comment]
I just set it up so that it sorts by the % of votes received in the first round, as a proxy for total # of votes. The trouble is, it's difficult to see when a choice switches from second to third.

I do think this change was phenomenal, though, for improving visibility. Please test and Let me know your thoughts.

**Comment by ggordn3r** [comment]
On this poll, 0% is ranked above 60%... thoughts? According to your comment, I would expect choices eliminated in Round 1 to appear at the bottom.
https://rankit-vote.appspot.com/results/h2rjTQZMM4PYtsDAbQZv/summary

![Results - Now that we've finished The Meaning of Marriage, what should our small group do next_ - RankIt](https://user-images.githubusercontent.com/10144772/71204638-97fe6500-226e-11ea-881c-491539173b30.png)

**Comment by ggordn3r** [comment]
See also this poll, which has eliminated choices above and below:
https://rankit-vote.appspot.com/results/HxP9Wblv4II1jRNg96gS/summary

**Comment by iambateman** [comment]
Doh. this is fixed. It wasn't sorting choices with zero votes.

**Comment by ggordn3r** [comment]
Note that the sorting is still behaving a little oddly in later rounds, for example 6-9 here: https://rankit.vote/results/t6glVsc1UJgHSwDiLwqp/6

However, because the initial values are sorted descending, I am closing this.
