### ISSUE TITLE
Add "updating results" message/icon when updating results

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#79]
A couple of beta testers were confused when the results changed while they were reading round summaries. I recommend adding some message or icon in the center of the view for 3-5 seconds that says "updating results", similar to a "loading" message, whenever an update occurs.

**Comment by iambateman** [comment]
Decision: freeze the view now
for 1.5: add a "presentation" view to allow for screens.

**Comment by iambateman** [comment]
I believe the view is frozen, such that someone won't see updating results as votes are cast.

This can be tested by opening two browser windows, pointed to:
1. http://localhost:4200/polls/MPKkESjLceOTx4xJAZ7c
2. http://localhost:4200/results/MPKkESjLceOTx4xJAZ7c/summary

cast a vote in the first window and see if it changes in the summary.
