### ISSUE TITLE
"Submit my vote" button (etc) needs hover state

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#8]
In order to be consistent with the Turquoise boxes, I think that the color of the submit button should change when you mouse over it. Same for the top buttons (back, home, account)

**Comment by iambateman** [comment]
This is fixed. Please confirm & close.

**Comment by oburbank** [comment]
still no feedback to the user when they mouse over the home (Rankit Icon), I think that changing the mouse to the finger pointing icon would suffice here.

**Comment by iambateman** [comment]
This is fixed!

**Comment by oburbank** [comment]
i don't see this fix.

**Comment by iambateman** [comment]
Were you looking at https://rankit-vote.appspot.com/home ? I'm definitely seeing it there.

**Comment by ggordn3r** [comment]
Hi Owen,

I'm seeing this fix. Are you using the link to the latest version?
https://rankit-vote.appspot.com/home

*Trey Gordner*
Founder, Koios
(803) 570-2144
Website <https://www.koios.co> | Twitter <https://twitter.com/koioslib> | Join
our Newsletter <https://www.koios.co/join-koios-newsletter/>
*Helping libraries show up online*
