### ISSUE TITLE
Should we stop showing results below a certain # of votes?

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#80]
Despite our best attempt with the "this poll doesn't have many votes yet" message, results with just a few votes are still confusing. The probability of too many winners (multi-way ties where there are more winners than seats), not enough winners (in multi-winner, where there are less votes than seats), and other edge cases is very high when there are not many votes.

Does it make more sense to hide the results below a certain number of votes (e.g. 7), or validate for certain edge cases? As I see it, hiding the results would entail a message like "There aren't many votes in this poll yet. When the poll has at least X votes, results will appear here. In the meantime, share the poll with others to see results sooner!"

Otherwise, we are going to need to write significantly more logic to handle these cases as they arise. Example of too many winners below, for context.

<img width="682" alt="Screen Shot 2019-10-23 at 9 54 01 AM" src="https://user-images.githubusercontent.com/10144772/67412772-e30d3c00-f58d-11e9-9a63-d2e4f43fe12c.png">

**Comment by ggordn3r** [comment]
Emily is ok with hiding results below a certain threshold.

**Comment by iambateman** [comment]
Ok, this is obviously a challenging one. Here's what i've done:
- increased the size of the 'the results are weird' note by 2x.
- added share buttons.
- added a note to share the poll to get more voters
- pulled the summary statements.

But I'm still showing the graph.

that feels like a happy medium to me. let me know what you think.

https://rankit.vote/results/F1rYPlMbtgXVPYLTNoc4/summary

**Comment by ggordn3r** [comment]
I think this is the right choice. Good call, especially on pulling summary statements.
