### ISSUE TITLE
Typo in "this poll doesn't have many votes yet" message

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#81]
See screenshot. Text should read:

> Heads up: this poll doesn't have many votes yet. Results are displayed below, but they will **be** more meaningful once more people have voted.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/10144772/67413782-d2f65c00-f58f-11e9-9c06-efbb7fe1302e.png">

**Comment by iambateman** [comment]
Thanks.

**Comment by iambateman** [comment]
This is done. will push shortly.
