### ISSUE TITLE
When top choice wins, new "X% to win" label is obscured

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#82]
Maybe add a few pixels between the label and the first bar? See screenshot.
![Screenshot (102)](https://user-images.githubusercontent.com/10144772/67414655-801da400-f591-11e9-9517-b7e0ef82c428.png)

**Comment by iambateman** [comment]
Once things propagate, please check again. Here's what I'm seeing:
https://www.dropbox.com/s/ge4b2ckaiqis3aa/Screenshot%202019-11-16%2011.27.53.jpg?dl=0
