### ISSUE TITLE
Results do not appear in some cases

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#90]
Several users report that they are unable to see results. See screenshots below. I am able to reproduce at the following URL:

https://rankit.vote/results/y644FmoM7b1T8lmAWAP4/summary

![Screen Rankit](https://user-images.githubusercontent.com/10144772/70375433-c887eb80-18cb-11ea-95c2-d605a2a003d3.png)

![Screenshot_20191206-064424_DuckDuckGo](https://user-images.githubusercontent.com/10144772/70375422-9bd3d400-18cb-11ea-853e-0338327c1ba9.jpg)

**Comment by iambateman** [comment]
Is this still happening for you? I'm seeing results here: https://rankit.vote/results/y644FmoM7b1T8lmAWAP4/summary

**Comment by iambateman** [comment]
ok..I pushed an update. I wasn't able to reproduce at that URL, but i think it had something to do with the tie statement. Let me know if you're still seeing it

**Comment by ggordn3r** [comment]
I'm getting results now at the URL I shared. Will send an update to those
who reported the bug to confirm that it is now resolved.
