### ISSUE TITLE
Extra round in poll

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#92]
It appears that Round 6 is unnecessary in this poll because 3 winners have been selected by Round 5. Am I misunderstanding something?

https://rankit-vote.appspot.com/results/HxP9Wblv4II1jRNg96gS/5

Also notice the inconsistency in the Round 6 title:

**Round 6 (Final Result)**
After _7 rounds_ and 23 votes...

**Comment by proggeramlug** [comment]
@iambateman you wrote the routine to get winners, any thoughts on this? you can probably answer this in 2 minutes and I need 2h :D

**Comment by iambateman** [comment]
I actually did not write the routine to get winners. That was provided as a standard JavaScript implementation.

But I do remember this being a weird edge case more than a prevalent, common issue.

Sorry...this is still open because I *couldn't* figure it out at the time.

**Comment by proggeramlug** [comment]
Found the problem and fixed it.

**Comment by ggordn3r** [comment]
Thanks. I'm not sure how to test this. Can you give me a test case to set up?

**Comment by proggeramlug** [comment]
Compare this: https://rankit.skelpo.com/results/HxP9Wblv4II1jRNg96gS/summary
To this: http://rankit.vote/results/HxP9Wblv4II1jRNg96gS/summary

**Comment by ggordn3r** [comment]
In comparing the old version to the new, I noticed an issue with the Round Summary in Round 4.

Compare:
https://rankit.skelpo.com/results/HxP9Wblv4II1jRNg96gS/4

To:
https://rankit.vote/results/HxP9Wblv4II1jRNg96gS/4

It appears that Round 4 is now pulling in the Poll Summary as its Round Summary and Round 5's is broken.

**Comment by proggeramlug** [comment]
Problem fixed.
