### ISSUE TITLE
Force HTTPS on App Engine

### ISSUE THREAD

**Issue by iambateman** [iambateman/RankIt#93]

**Comment by proggeramlug** [comment]
Done now, please test.

**Comment by ggordn3r** [comment]
If I change https://rankit.vote/polls to http://rankit.vote/polls, the request never ends. The expected behavior is that it automatically redirects to HTTPS.

![Screenshot (291)](https://user-images.githubusercontent.com/10144772/81480310-e64cda00-91f6-11ea-9f3a-f766632f0cd8.png)

**Comment by proggeramlug** [comment]
Fixed now!
