### ISSUE TITLE
Change final after results to "Finish" instead of "Continue"

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#94]
Emily asked to change the text on the bottom-right from "Continue" to "Finish" to meet user expectations that this is the last view in the results.

![Screenshot (218)](https://user-images.githubusercontent.com/10144772/72022897-8a217b80-323f-11ea-84a9-669060f771eb.png)

**Comment by iambateman** [comment]
Can all bugs be like this?

:)

Fixed.
