### ISSUE TITLE
Slight language change in Round Summary

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#95]
"1: The current RCV process description is the style that gives the impression that some people are getting to vote more than other people.  I like this description:
'All ballots are counted in each round and your vote goes to the candidate you ranked highest (among those candidates still in the running).'"
~ Chris Mason <chris.mason@fairvotewa.org>

For context, here is the current description:
_With Ranked Choice Voting (RCV), voters get to rank candidates in order of choice. If a candidate receives more than half of the first choices, they win, just like any other election. If not, the candidate with the fewest votes is eliminated, and voters who picked that candidate as ‘number 1’ will have their votes count for their next choice.This process continues until a candidate wins with more than half of the votes._

**Comment by proggeramlug** [comment]
This can be tested now.

**Comment by ggordn3r** [comment]
@proggeramlug Messed up on this one--I need one of those sentences added back. The final copy should read:

With Ranked Choice Voting (RCV), voters get to rank candidates in order of choice. All ballots are counted in each round and your vote goes to the candidate you ranked highest (among those candidates still in the running).

**Comment by proggeramlug** [comment]
Fixed now!

**Comment by ggordn3r** [comment]
This seems to work correctly on single-winner polls, but not on polls with multiple winners.

Compare (1 winner, correct):
https://rankit.skelpo.com/results/h2rjTQZMM4PYtsDAbQZv/summary

To (many winners, still the old language):
https://rankit.skelpo.com/results/HxP9Wblv4II1jRNg96gS/summary

Here is how it currently reads:

```
After 6 rounds and 25 votes, Sen. Elizabeth Warren of Massachusetts, South Bend, Indiana, Mayor Pete Buttigieg, and Sen. Kamala Harris of California win.

In a multi-winner ranked choice voting poll with 3 winners, each winner must get at least 25% of the vote or be the last choice standing. The percentage of votes required (threshold) depends on how many seats are being elected - the more seats there are to fill, the lower the percentage needed to win.

Voters rank candidates in order of choice. If no candidate meets the percentage of votes needed to win, the candidate with the lowest number of votes is eliminated and voters who picked that candidate will have their votes count for their next choice. If a candidate does meet the percentage of votes needed, any extra votes count proportionally toward voters’ next choices.
```

Here is how it should read:

```
After 6 rounds and 25 votes, Sen. Elizabeth Warren of Massachusetts, South Bend, Indiana, Mayor Pete Buttigieg, and Sen. Kamala Harris of California win.

With Ranked Choice Voting (RCV), voters get to rank candidates in order of choice. All ballots are counted in each round and your vote goes to the candidate you ranked highest (among those candidates still in the running).

In a multi-winner ranked choice voting poll with 3 winners, each winner must get at least 25% of the vote or be the last choice standing. The percentage of votes required (threshold) depends on how many seats are being elected - the more seats there are to fill, the lower the percentage needed to win. If a candidate passes the threshold, extra votes count toward their voters’ next choices.
```

**Comment by proggeramlug** [comment]
This is fixed now!
