### ISSUE TITLE
Poll Creation: Hitting [Enter] after typing a choice deletes it

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#97]
This is a wacky one:

"Create a poll, enter something in the first option text input, then hit Return. Instead of going to the next text input, it deletes the final one. This happens even if you’re already in the final one -- it will delete the option you just typed in."

**Comment by iambateman** [comment]
I re-mapped `Enter/return` to do nothing when it's tapped there. That's so weird.
