### ISSUE TITLE
As a poll creator, I can export results data to RCVIS

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#99]
Some people in the advisory group really seem to like the visualizations on RCVIS. Rather than recreate them within RankIt, we should enable users to export the results in a format that can be imported into RCVIS:
https://www.rcvis.com/upload.html

I think "poll creator" is the right role for this. Shouldn't be limited to admin, but probably too confusing for a typical person voting and sharing.

At the same time this is enabled, we should also remove "/raw", which is our current workaround (and a security liability).

- This should appear as a new purple button underneath the others called "Download results (CSV)"
- This button should be disabled when polls are open and enabled when polls are closed.

**Comment by ggordn3r** [comment]
#116 enhances this by pushing JSON to RCVIS. It's another open-source project and the developer is willing to assist on his end.

**Comment by proggeramlug** [comment]
@ggordn3r It sounds like this is already implemented? If so where, what do you mean by "/raw"?

**Comment by ggordn3r** [comment]
No, it's not implemented. Stephen just built in a way to inspect the raw votes:

Here's an example poll:
https://rankit.vote/results/zDvGganVwjdYGafT2mLh/summary 

And here's the JSON for it:
https://rankit.vote/results/zDvGganVwjdYGafT2mLh/raw

Appending "/raw" will work for any poll. But you just see the raw votes in JSON.

**Comment by ggordn3r** [comment]
Some users have said that they want to be able to download a CSV of results
so they can look at them in a spreadsheet, independent of the request for
RCVIS. So ideally we should give them both options.

*Trey Gordner*
Founder, Koios
(803) 570-2144
Website <https://www.koios.co> | Twitter <https://twitter.com/koioslib> | Join
our Newsletter <https://www.koios.co/join-koios-newsletter/>
*Helping libraries show up online*

**Comment by proggeramlug** [comment]
This is implemented now, check it out!

**Comment by ggordn3r** [comment]
This is cool! One question--I'm noticing a blank vote in one of the polls I downloaded (see row 7 in the spreadsheet). Shouldn't that be impossible?


Choice 1 | Choice 2 | Choice 3 | Choice 4 | createdAt
-- | -- | -- | -- | --
Discuss a new topic every week (members   suggest ideas) | Read a new contemporary Christian   book together | Follow the Genesis sermon series | Study a book of the Bible besides   Genesis | 1.57E+12
Study a book of the Bible besides Genesis | Read a new contemporary Christian   book together | Follow the Genesis sermon series | Discuss a new topic every week   (members suggest ideas) | 1.57E+12
Discuss a new topic every week (members   suggest ideas) | Read a new contemporary Christian   book together | Study a book of the Bible besides   Genesis | Follow the Genesis sermon series | 1.57E+12
Discuss a new topic every week (members   suggest ideas) | Follow the Genesis sermon series | Study a book of the Bible besides   Genesis | Read a new contemporary Christian   book together | 1.57E+12
Discuss a new topic every week (members   suggest ideas) | Study a book of the Bible besides   Genesis | Follow the Genesis sermon series |   | 1.57E+12
  |   |   |   | 1.59E+12
Study a book of the Bible besides Genesis | Discuss a new topic every week   (members suggest ideas) | Read a new contemporary Christian   book together | Follow the Genesis sermon series | 1.57E+12
Discuss a new topic every week (members   suggest ideas) | Read a new contemporary Christian   book together | Study a book of the Bible besides   Genesis | Follow the Genesis sermon series | 1.57E+12
Study a book of the Bible besides Genesis | Discuss a new topic every week   (members suggest ideas) | Read a new contemporary Christian   book together | Follow the Genesis sermon series | 1.57E+12
Read a new contemporary Christian book   together |   |   |   | 1.57E+12
Discuss a new topic every week (members   suggest ideas) | Follow the Genesis sermon series | Study a book of the Bible besides   Genesis | Read a new contemporary Christian   book together | 1.57E+12

**Comment by proggeramlug** [comment]
@ggordn3r Probably an error when testing or working on it. The entry is actually empty. Do we want to filter such votes? I have no clue how many there are in the system.

BTW: I happened: 04/24/2020 @ 9:29pm

**Comment by ggordn3r** [comment]
I'm going to mark this as closed on the assumption that it's a legacy issue, but if beta testers report empty entries, I'll open it again.

**Comment by ggordn3r** [comment]
Actually, one last small thing: can you disable the "Download CSV" button when Voters = 0?

**Comment by proggeramlug** [comment]
Done!

**Comment by ggordn3r** [comment]
Thanks! One more: can you use fa-table for the Download CSV icon instead of fa-pencil?
https://fontawesome.com/v4.7.0/icon/table

**Comment by proggeramlug** [comment]
Done
